In [2]:
import numpy as np
import pandas as pd

In [3]:
cd ../DataSets/

/Users/alexandersu/Documents/Vemgoo/vmg-prelim/DataSets

In [8]:
wind=pd.read_csv('USA_wind.csv')
temp=pd.read_csv('USA_city_temps.csv')
city=pd.read_csv('city_attributes.csv')
city_final=pd.read_csv('city_attributes.csv')

In [21]:
#scoring for wind
Jan_score=[]

for x in wind['Jan']:
    if x > 3.49:
        Jan_score.append(float('6')),    
    elif x > 3.013:
        Jan_score.append(float('5')),
    elif x > 2.686:
        Jan_score.append(float('4')), 
    elif x > 2.164:
        Jan_score.append(float('3')),
    elif x > 1.104:
        Jan_score.append(float('2')), 
    else:
        Jan_score.append(float('1')),
city["jan_score_temp"]=Jan_score

Feb_score=[]

for x in wind['Feb']:
    if x > 3.49:
        Feb_score.append(float('6')),    
    elif x > 3.013:
        Feb_score.append(float('5')),
    elif x > 2.686:
        Feb_score.append(float('4')), 
    elif x > 2.164:
        Feb_score.append(float('3')),
    elif x > 1.104:
        Feb_score.append(float('2')), 
    else:
        Feb_score.append(float('1')),

city["feb_score_temp"]=Feb_score

Mar_score=[]
for x in wind['Mar']:
    if x > 3.49:
        Mar_score.append(float('6')),    
    elif x > 3.013:
        Mar_score.append(float('5')),
    elif x > 2.686:
        Mar_score.append(float('4')), 
    elif x > 2.164:
        Mar_score.append(float('3')),
    elif x > 1.104:
        Mar_score.append(float('2')), 
    else:
        Mar_score.append(float('1')),
city["mar_score_temp"]=Mar_score

Apr_score=[]
for x in wind['Apr']:
    if x > 3.49:
        Apr_score.append(float('6')),    
    elif x > 3.013:
        Apr_score.append(float('5')),
    elif x > 2.686:
        Apr_score.append(float('4')), 
    elif x > 2.164:
        Apr_score.append(float('3')),
    elif x > 1.104:
        Apr_score.append(float('2')), 
    else:
        Apr_score.append(float('1')),
city["apr_score_temp"]=Apr_score

May_score=[]
for x in wind['May']:
    if x > 3.49:
        May_score.append(float('6')),    
    elif x > 3.013:
        May_score.append(float('5')),
    elif x > 2.686:
        May_score.append(float('4')), 
    elif x > 2.164:
        May_score.append(float('3')),
    elif x > 1.104:
        May_score.append(float('2')), 
    else:
        May_score.append(float('1')),
city["may_score_temp"]=May_score

Jun_score=[]
for x in wind['Jun']:
    if x > 3.49:
        Jun_score.append(float('6')),    
    elif x > 3.013:
        Jun_score.append(float('5')),
    elif x > 2.686:
        Jun_score.append(float('4')), 
    elif x > 2.164:
        Jun_score.append(float('3')),
    elif x > 1.104:
        Jun_score.append(float('2')), 
    else:
        Jun_score.append(float('1')),
city["jun_score_temp"]=Jun_score

Jul_score=[]
for x in wind['Jul']:
    if x > 3.49:
        Jul_score.append(float('6')),    
    elif x > 3.013:
        Jul_score.append(float('5')),
    elif x > 2.686:
        Jul_score.append(float('4')), 
    elif x > 2.164:
        Jul_score.append(float('3')),
    elif x > 1.104:
        Jul_score.append(float('2')), 
    else:
        Jul_score.append(float('1')),
city["jul_score_temp"]=Jul_score

Aug_score=[]
for x in wind['Aug']:
    if x > 3.49:
        Aug_score.append(float('6')),    
    elif x > 3.013:
        Aug_score.append(float('5')),
    elif x > 2.686:
        Aug_score.append(float('4')), 
    elif x > 2.164:
        Aug_score.append(float('3')),
    elif x > 1.104:
        Aug_score.append(float('2')), 
    else:
        Aug_score.append(float('1')),
city["aug_score_temp"]=Aug_score

Sep_score=[]
for x in wind['Sep']:
    if x > 3.49:
        Sep_score.append(float('6')),    
    elif x > 3.013:
        Sep_score.append(float('5')),
    elif x > 2.686:
        Sep_score.append(float('4')), 
    elif x > 2.164:
        Sep_score.append(float('3')),
    elif x > 1.104:
        Sep_score.append(float('2')), 
    else:
        Sep_score.append(float('1')),
city["sep_score_temp"]=Sep_score

Oct_score=[]
for x in wind['Oct']:
    if x > 3.49:
        Oct_score.append(float('6')),    
    elif x > 3.013:
        Oct_score.append(float('5')),
    elif x > 2.686:
        Oct_score.append(float('4')), 
    elif x > 2.164:
        Oct_score.append(float('3')),
    elif x > 1.104:
        Oct_score.append(float('2')), 
    else:
        Oct_score.append(float('1')),
city["oct_score_temp"]=Oct_score

Nov_score=[]
for x in wind['Nov']:
    if x > 3.49:
        Nov_score.append(float('6')),    
    elif x > 3.013:
        Nov_score.append(float('5')),
    elif x > 2.686:
        Nov_score.append(float('4')), 
    elif x > 2.164:
        Nov_score.append(float('3')),
    elif x > 1.104:
        Nov_score.append(float('2')), 
    else:
        Nov_score.append(float('1')),
city["nov_score_temp"]=Nov_score


Dec_score=[]
for x in wind['Dec']:
    if x > 3.49:
        Dec_score.append(float('6')),    
    elif x > 3.013:
        Dec_score.append(float('5')),
    elif x > 2.686:
        Dec_score.append(float('4')), 
    elif x > 2.164:
        Dec_score.append(float('3')),
    elif x > 1.104:
        Dec_score.append(float('2')), 
    else:
        Dec_score.append(float('1')),
city["dec_score_temp"]=Dec_score

In [25]:
#scoring for temperature
# For January
Jan_score=[]

for x in temp['Jan']:
    if x > 23.888:
        Jan_score.append(float('1'))
    elif x > 15.555:
        Jan_score.append(float('0.75'))
    elif x > 12.7: 
        Jan_score.append(float('0.5'))
    elif x > 10:
        Jan_score.append(float('0.25'))
    else:
        Jan_score.append(float('0'))
city["jan_score_wind"]=Jan_score    

# For Feb
Feb_score=[]

for x in temp['Feb']:
    if x > 23.888:
        Feb_score.append(float('1'))
    elif x > 15.555:
        Feb_score.append(float('0.75'))
    elif x > 12.7: 
        Feb_score.append(float('0.5'))
    elif x > 10:
        Feb_score.append(float('0.25'))
    else:
        Feb_score.append(float('0'))
city["feb_score_wind"]=Feb_score      

# For March
Mar_score=[]

for x in temp['Mar']:
    if x > 23.888:
        Mar_score.append(float('1'))
    elif x > 15.555:
        Mar_score.append(float('0.75'))
    elif x > 12.7: 
        Mar_score.append(float('0.5'))
    elif x > 10:
        Mar_score.append(float('0.25'))
    else:
        Mar_score.append(float('0'))
city["mar_score_wind"]=Mar_score        
        
# For April
Apr_score=[]

for x in temp['Apr']:
    if x > 23.888:
        Apr_score.append(float('1'))
    elif x > 15.555:
        Apr_score.append(float('0.75'))
    elif x > 12.7: 
        Apr_score.append(float('0.5'))
    elif x > 10:
        Apr_score.append(float('0.25'))
    else:
        Apr_score.append(float('0'))
city["apr_score_wind"]=Apr_score

# For May
May_score=[]

for x in temp['May']:
    if x > 23.888:
        May_score.append(float('1'))
    elif x > 15.555:
        May_score.append(float('0.75'))
    elif x > 12.7: 
        May_score.append(float('0.5'))
    elif x > 10:
        May_score.append(float('0.25'))
    else:
        May_score.append(float('0'))
city["may_score_wind"]=May_score

# For June
Jun_score=[]

for x in temp['Jun']:
    if x > 23.888:
        Jun_score.append(float('1'))
    elif x > 15.555:
        Jun_score.append(float('0.75'))
    elif x > 12.7: 
        Jun_score.append(float('0.5'))
    elif x > 10:
        Jun_score.append(float('0.25'))
    else:
        Jun_score.append(float('0'))
city["jun_score_wind"]=Jun_score

# For July
Jul_score=[]

for x in temp['Jul']:
    if x > 23.888:
        Jul_score.append(float('1'))
    elif x > 15.555:
        Jul_score.append(float('0.75'))
    elif x > 12.7: 
        Jul_score.append(float('0.5'))
    elif x > 10:
        Jul_score.append(float('0.25'))
    else:
        Jul_score.append(float('0'))
city["jul_score_wind"]=Jul_score

# For August
Aug_score=[]

for x in temp['Aug']:
    if x > 23.888:
        Aug_score.append(float('1'))
    elif x > 15.555:
        Aug_score.append(float('0.75'))
    elif x > 12.7: 
        Aug_score.append(float('0.5'))
    elif x > 10:
        Aug_score.append(float('0.25'))
    else:
        Aug_score.append(float('0'))
city["aug_score_wind"]=Aug_score

# For September
Sep_score = []

for x in temp['Sep']:
    if x > 23.888:
        Sep_score.append(float('1'))
    elif x > 15.555:
        Sep_score.append(float('0.75'))
    elif x > 12.7: 
        Sep_score.append(float('0.5'))
    elif x > 10:
        Sep_score.append(float('0.25'))
    else:
        Sep_score.append(float('0'))
city["sep_score_wind"]=Sep_score

# For October
Oct_score = []

for x in temp['Oct']:
    if x > 23.888:
        Oct_score.append(float('1'))
    elif x > 15.555:
        Oct_score.append(float('0.75'))
    elif x > 12.7: 
        Oct_score.append(float('0.5'))
    elif x > 10:
        Oct_score.append(float('0.25'))
    else:
        Oct_score.append(float('0'))
city["oct_score_wind"]=Oct_score

# For November
Nov_score = []

for x in temp['Nov']:
    if x > 23.888:
        Nov_score.append(float('1'))
    elif x > 15.555:
        Nov_score.append(float('0.75'))
    elif x > 12.7: 
        Nov_score.append(float('0.5'))
    elif x > 10:
        Nov_score.append(float('0.25'))
    else:
        Nov_score.append(float('0'))
city["nov_score_wind"]=Nov_score

# For December
Dec_score = []

for x in temp['Dec']:
    if x > 23.888:
        Dec_score.append(float('1'))
    elif x > 15.555:
        Dec_score.append(float('0.75'))
    elif x > 12.7: 
        Dec_score.append(float('0.5'))
    elif x > 10:
        Dec_score.append(float('0.25'))
    else:
        Dec_score.append(float('0'))
city["dec_score_wind"]=Dec_score

In [26]:
city_final['Jan_total_score']=city['jan_score_temp'] + city['jan_score_wind']
city_final['Feb_total_score']=city['feb_score_temp'] + city['feb_score_wind']
city_final['Mar_total_score']=city['mar_score_temp'] + city['mar_score_wind']
city_final['Apr_total_score']=city['apr_score_temp'] + city['apr_score_wind']
city_final['May_total_score']=city['may_score_temp'] + city['may_score_wind']
city_final['Jun_total_score']=city['jun_score_temp'] + city['jun_score_wind']
city_final['Jul_total_score']=city['jul_score_temp'] + city['jul_score_wind']
city_final['Sep_total_score']=city['sep_score_temp'] + city['sep_score_wind']
city_final['Aug_total_score']=city['aug_score_temp'] + city['aug_score_wind']
city_final['Nov_total_score']=city['nov_score_temp'] + city['nov_score_wind']
city_final['Dec_total_score']=city['oct_score_temp'] + city['oct_score_wind']
city_final['Dec_total_score']=city['dec_score_temp'] + city['dec_score_wind']

In [27]:
city_final

,City,Country,Latitude,Longitude,Jan_total_score,Feb_total_score,Mar_total_score,Apr_total_score,May_total_score,Jun_total_score,Jul_total_score,Sep_total_score,Aug_total_score,Nov_total_score,Dec_total_score
0,Vancouver,Canada,49.249660,-123.119339,2.00,3.00,4.00,3.00,2.50,2.75,3.75,3.50,3.75,4.00,3.00
1,Portland,United States,45.523449,-122.676208,3.00,3.00,3.00,2.25,2.50,2.75,2.75,2.75,2.75,3.00,3.00
2,San Francisco,United States,37.774929,-122.419418,3.25,5.25,5.50,6.50,5.75,3.75,4.75,3.75,3.75,3.50,4.25
3,Seattle,United States,47.606209,-122.332069,2.00,3.00,3.00,3.25,2.50,2.75,2.75,2.75,2.75,3.00,3.00
4,Los Angeles,United States,34.052231,-118.243683,2.25,1.50,2.50,2.75,2.75,2.75,2.75,2.75,2.75,1.50,2.25
5,San Diego,United States,32.715328,-117.157257,2.25,2.50,2.50,3.75,2.75,2.75,2.75,2.75,2.75,2.50,2.25
6,Las Vegas,United States,36.174969,-115.137222,3.00,3.25,4.75,5.75,5.75,4.00,5.00,4.00,4.00,3.25,2.00
7,Phoenix,United States,33.448380,-112.074043,2.25,2.50,2.75,3.75,3.00,3.00,4.00,3.00,3.00,2.75,2.25
8,Albuquerque,United States,35.084492,-106.651138,3.00,4.00,5.00,6.25,5.75,3.75,4.75,3.75,3.75,3.00,3.00
9,Denver,United States,39.739151,-104.984703,3.00,5.00,5.00,5.00,3.25,2.75,3.75,3.75,2.75,3.00,3.00
10,San Antonio,United States,29.424120,-98.493629,4.25,5.50,5.75,5.75,6.75,5.00,6.00,4.00,5.00,3.75,3.25
11,Dallas,United States,32.783058,-96.806671,5.00,6.25,6.50,6.75,6.75,7.00,7.00,6.00,5.00,6.50,5.00
12,Houston,United States,29.763281,-95.363274,4.25,6.50,6.75,6.75,5.75,4.00,4.00,4.00,4.00,4.75,4.50
13,Kansas City,United States,39.099731,-94.578568,5.00,6.00,6.00,6.50,5.75,6.00,6.00,5.75,5.00,6.00,4.00
14,Minneapolis,United States,44.979969,-93.263840,5.00,6.00,6.00,6.00,6.50,5.75,5.75,5.75,3.75,6.00,5.00
15,Saint Louis,United States,38.627270,-90.197891,5.00,6.00,6.00,6.50,4.75,4.00,4.00,3.75,4.00,5.00,4.00
16,Chicago,United States,41.850029,-87.650047,6.00,6.00,6.00,6.00,5.50,4.75,5.75,5.75,4.75,6.00,6.00
17,Nashville,United States,36.165890,-86.784439,4.00,5.00,5.00,5.75,3.75,3.00,3.00,2.75,3.00,3.00,4.00
18,Indianapolis,United States,39.768379,-86.158043,6.00,6.00,6.00,6.25,5.75,3.75,4.75,3.75,2.75,5.00,5.00
19,Atlanta,United States,33.749001,-84.387978,3.00,4.00,4.25,3.75,3.75,3.00,3.00,2.75,3.00,3.25,3.00
20,Detroit,United States,42.331429,-83.045753,5.00,6.00,5.00,6.00,5.50,4.75,3.75,3.75,3.75,6.00,5.00
21,Jacksonville,United States,30.332180,-81.655647,4.50,5.50,5.75,5.75,4.75,4.00,5.00,4.00,4.00,5.75,3.75
22,Charlotte,United States,35.227089,-80.843132,3.00,4.00,4.25,4.75,3.75,3.00,3.00,3.75,3.00,3.00,2.00
23,Miami,United States,25.774269,-80.193657,5.75,5.75,5.75,7.00,6.00,5.00,5.00,5.00,5.00,6.75,4.75
24,Pittsburgh,United States,40.440620,-79.995888,4.00,5.00,5.00,5.25,3.75,2.75,2.75,2.75,2.75,4.00,4.00
25,Toronto,Canada,43.700111,-79.416298,6.00,6.00,6.00,6.00,5.50,4.75,4.75,4.75,4.75,6.00,6.00
26,Philadelphia,United States,39.952339,-75.163788,4.00,5.00,5.00,5.25,3.75,2.75,4.00,3.75,2.75,4.00,3.00
27,New York,United States,40.714272,-74.005966,6.00,6.00,6.00,6.25,3.75,3.75,4.00,4.75,3.75,6.00,5.00
28,Montreal,Canada,45.508839,-73.587807,6.00,6.00,6.00,6.00,6.50,5.75,5.75,5.75,5.75,6.00,6.00
29,Boston,United States,42.358429,-71.059769,6.00,6.00,6.00,6.00,5.50,4.75,4.75,4.75,3.75,6.00,5.00
30,Beersheba,Israel,31.251810,34.791302,2.00,2.25,3.50,3.75,2.75,2.75,3.00,2.75,3.00,2.50,2.25
31,Tel Aviv District,Israel,32.083328,34.799999,4.50,3.50,4.75,4.75,4.75,4.00,5.00,5.00,5.00,3.75,3.50
32,Eilat,Israel,29.558050,34.948212,4.50,3.50,4.75,4.75,7.00,7.00,7.00,7.00,7.00,5.75,4.50
33,Haifa,Israel,32.815559,34.989170,6.50,6.75,6.75,6.75,5.75,5.00,5.00,5.00,5.00,5.75,5.75
34,Nahariyya,Israel,33.005859,35.094090,6.50,5.50,6.75,5.75,3.75,4.00,5.00,5.00,4.00,5.75,5.50
35,Jerusalem,Israel,31.769039,35.216331,2.25,2.50,2.75,2.75,2.75,3.00,3.00,3.00,3.00,2.75,2.50