In [2]:
import numpy as np
import pandas as pd

In [3]:
cd ../DataSets/

/Users/alexandersu/Documents/Vemgoo/vmg-prelim/DataSets

In [4]:
wind=pd.read_csv('USA_wind.csv')
temp=pd.read_csv('USA_city_temps.csv')
city=pd.read_csv('city_attributes.csv')
rain=pd.read_csv('USA_rain_average.csv')
city_final=pd.read_csv('city_attributes.csv')

#scoring for wind
Jan_score=[]

for x in wind['Jan']:
    if x > 3.49:
        Jan_score.append(float('3')),    
    elif x > 3.013:
        Jan_score.append(float('2.5')),
    elif x > 2.686:
        Jan_score.append(float('2')), 
    elif x > 2.164:
        Jan_score.append(float('1.5')),
    elif x > 1.104:
        Jan_score.append(float('1')), 
    else:
        Jan_score.append(float('.5')),
city["jan_score_wind"]=Jan_score

Feb_score=[]

for x in wind['Feb']:
    if x > 3.49:
        Feb_score.append(float('3')),    
    elif x > 3.013:
        Feb_score.append(float('2.5')),
    elif x > 2.686:
        Feb_score.append(float('2')), 
    elif x > 2.164:
        Feb_score.append(float('1.5')),
    elif x > 1.104:
        Feb_score.append(float('1')), 
    else:
        Feb_score.append(float('.5')),

city["feb_score_wind"]=Feb_score

Mar_score=[]
for x in wind['Mar']:
    if x > 3.49:
        Mar_score.append(float('3')),    
    elif x > 3.013:
        Mar_score.append(float('2.5')),
    elif x > 2.686:
        Mar_score.append(float('2')), 
    elif x > 2.164:
        Mar_score.append(float('1.5')),
    elif x > 1.104:
        Mar_score.append(float('1')), 
    else:
        Mar_score.append(float('.5')),
city["mar_score_wind"]=Mar_score

Apr_score=[]
for x in wind['Apr']:
    if x > 3.49:
        Apr_score.append(float('3')),    
    elif x > 3.013:
        Apr_score.append(float('2.5')),
    elif x > 2.686:
        Apr_score.append(float('2')), 
    elif x > 2.164:
        Apr_score.append(float('1.5')),
    elif x > 1.104:
        Apr_score.append(float('1')), 
    else:
        Apr_score.append(float('.5')),
city["apr_score_wind"]=Apr_score

May_score=[]
for x in wind['May']:
    if x > 3.49:
        May_score.append(float('3')),    
    elif x > 3.013:
        May_score.append(float('2.5')),
    elif x > 2.686:
        May_score.append(float('2')), 
    elif x > 2.164:
        May_score.append(float('1.5')),
    elif x > 1.104:
        May_score.append(float('1')), 
    else:
        May_score.append(float('.5')),
city["may_score_wind"]=May_score

Jun_score=[]
for x in wind['Jun']:
    if x > 3.49:
        Jun_score.append(float('3')),    
    elif x > 3.013:
        Jun_score.append(float('2.5')),
    elif x > 2.686:
        Jun_score.append(float('2')), 
    elif x > 2.164:
        Jun_score.append(float('1.5')),
    elif x > 1.104:
        Jun_score.append(float('1')), 
    else:
        Jun_score.append(float('.5')),
city["jun_score_wind"]=Jun_score

Jul_score=[]
for x in wind['Jul']:
    if x > 3.49:
        Jul_score.append(float('3')),    
    elif x > 3.013:
        Jul_score.append(float('2.5')),
    elif x > 2.686:
        Jul_score.append(float('2')), 
    elif x > 2.164:
        Jul_score.append(float('1.5')),
    elif x > 1.104:
        Jul_score.append(float('1')), 
    else:
        Jul_score.append(float('.5')),
city["jul_score_wind"]=Jul_score

Aug_score=[]
for x in wind['Aug']:
    if x > 3.49:
        Aug_score.append(float('3')),    
    elif x > 3.013:
        Aug_score.append(float('2.5')),
    elif x > 2.686:
        Aug_score.append(float('2')), 
    elif x > 2.164:
        Aug_score.append(float('1.5')),
    elif x > 1.104:
        Aug_score.append(float('1')), 
    else:
        Aug_score.append(float('.5')),
city["aug_score_wind"]=Aug_score

Sep_score=[]
for x in wind['Sep']:
    if x > 3.49:
        Sep_score.append(float('3')),    
    elif x > 3.013:
        Sep_score.append(float('2.5')),
    elif x > 2.686:
        Sep_score.append(float('2')), 
    elif x > 2.164:
        Sep_score.append(float('1.5')),
    elif x > 1.104:
        Sep_score.append(float('1')), 
    else:
        Sep_score.append(float('.5')),
city["sep_score_wind"]=Sep_score

Oct_score=[]
for x in wind['Oct']:
    if x > 3.49:
        Oct_score.append(float('3')),    
    elif x > 3.013:
        Oct_score.append(float('2.5')),
    elif x > 2.686:
        Oct_score.append(float('2')), 
    elif x > 2.164:
        Oct_score.append(float('1.5')),
    elif x > 1.104:
        Oct_score.append(float('1')), 
    else:
        Oct_score.append(float('.5')),
city["oct_score_wind"]=Oct_score

Nov_score=[]
for x in wind['Nov']:
    if x > 3.49:
        Nov_score.append(float('3')),    
    elif x > 3.013:
        Nov_score.append(float('2.5')),
    elif x > 2.686:
        Nov_score.append(float('2')), 
    elif x > 2.164:
        Nov_score.append(float('1.5')),
    elif x > 1.104:
        Nov_score.append(float('1')), 
    else:
        Nov_score.append(float('.5')),
city["nov_score_wind"]=Nov_score


Dec_score=[]
for x in wind['Dec']:
    if x > 3.49:
        Dec_score.append(float('3')),    
    elif x > 3.013:
        Dec_score.append(float('2.5')),
    elif x > 2.686:
        Dec_score.append(float('2')), 
    elif x > 2.164:
        Dec_score.append(float('1.5')),
    elif x > 1.104:
        Dec_score.append(float('1')), 
    else:
        Dec_score.append(float('.5')),
city["dec_score_wind"]=Dec_score

In [5]:
#scoring for temperature
# For January
Jan_score=[]

for x in temp['Jan']:
    if x > 26.667:
        Jan_score.append(float('6'))
    elif x > 23.888:
        Jan_score.append(float('5'))
    elif x > 21.11: 
        Jan_score.append(float('4'))
    elif x > 15.55:
        Jan_score.append(float('3'))
    elif x > 12.7:
        Jan_score.append(float('2'))
    else:
        Jan_score.append(float('1'))
city["jan_score_temp"]=Jan_score    

# For Feb
Feb_score=[]

for x in temp['Feb']:
    if x > 26.667:
        Feb_score.append(float('6'))
    elif x > 23.888:
        Feb_score.append(float('5'))
    elif x > 21.11: 
        Feb_score.append(float('4'))
    elif x > 15.55:
        Feb_score.append(float('3'))
    elif x > 12.7:
        Feb_score.append(float('2'))
    else:
        Feb_score.append(float('1'))
city["feb_score_temp"]=Feb_score      

# For March
Mar_score=[]

for x in temp['Mar']:
    if x > 26.667:
        Mar_score.append(float('6'))
    elif x > 23.888:
        Mar_score.append(float('5'))
    elif x > 21.11: 
        Mar_score.append(float('4'))
    elif x > 15.55:
        Mar_score.append(float('3'))
    elif x > 12.7:
        Mar_score.append(float('2'))
    else:
        Mar_score.append(float('1'))
city["mar_score_temp"]=Mar_score        
        
# For April
Apr_score=[]

for x in temp['Apr']:
    if x > 26.667:
        Apr_score.append(float('6'))
    elif x > 23.888:
        Apr_score.append(float('5'))
    elif x > 21.11: 
        Apr_score.append(float('4'))
    elif x > 15.55:
        Apr_score.append(float('3'))
    elif x > 12.7:
        Apr_score.append(float('2'))
    else:
        Apr_score.append(float('1'))
city["apr_score_temp"]=Apr_score

# For May
May_score=[]

for x in temp['May']:
    if x > 26.667:
        May_score.append(float('6'))
    elif x > 23.888:
        May_score.append(float('5'))
    elif x > 21.11: 
        May_score.append(float('4'))
    elif x > 15.55:
        May_score.append(float('3'))
    elif x > 12.7:
        May_score.append(float('2'))
    else:
        May_score.append(float('1'))
city["may_score_temp"]=May_score

# For June
Jun_score=[]

for x in temp['Jun']:
    if x > 26.667:
        Jun_score.append(float('6'))
    elif x > 23.888:
        Jun_score.append(float('5'))
    elif x > 21.11: 
        Jun_score.append(float('4'))
    elif x > 15.55:
        Jun_score.append(float('3'))
    elif x > 12.7:
        Jun_score.append(float('2'))
    else:
        Jun_score.append(float('1'))
city["jun_score_temp"]=Jun_score

# For July
Jul_score=[]

for x in temp['Jul']:
    if x > 26.667:
        Jul_score.append(float('6'))
    elif x > 23.888:
        Jul_score.append(float('5'))
    elif x > 21.11: 
        Jul_score.append(float('4'))
    elif x > 15.55:
        Jul_score.append(float('3'))
    elif x > 12.7:
        Jul_score.append(float('2'))
    else:
        Jul_score.append(float('1'))
city["jul_score_temp"]=Jul_score

# For August
Aug_score=[]

for x in temp['Aug']:
    if x > 26.667:
        Aug_score.append(float('6'))
    elif x > 23.888:
        Aug_score.append(float('5'))
    elif x > 21.11: 
        Aug_score.append(float('4'))
    elif x > 15.55:
        Aug_score.append(float('3'))
    elif x > 12.7:
        Aug_score.append(float('2'))
    else:
        Aug_score.append(float('1'))
city["aug_score_temp"]=Aug_score

# For September
Sep_score = []

for x in temp['Sep']:
    if x > 26.667:
        Sep_score.append(float('6'))
    elif x > 23.888:
        Sep_score.append(float('5'))
    elif x > 21.11: 
        Sep_score.append(float('4'))
    elif x > 15.55:
        Sep_score.append(float('3'))
    elif x > 12.7:
        Sep_score.append(float('2'))
    else:
        Sep_score.append(float('1'))
city["sep_score_temp"]=Sep_score

# For October
Oct_score = []

for x in temp['Oct']:
    if x > 26.667:
        Oct_score.append(float('6'))
    elif x > 23.888:
        Oct_score.append(float('5'))
    elif x > 21.11: 
        Oct_score.append(float('4'))
    elif x > 15.55:
        Oct_score.append(float('3'))
    elif x > 12.7:
        Oct_score.append(float('2'))
    else:
        Oct_score.append(float('1'))
city["oct_score_temp"]=Oct_score

# For November
Nov_score = []

for x in temp['Nov']:
    if x > 26.667:
        Nov_score.append(float('6'))
    elif x > 23.888:
        Nov_score.append(float('5'))
    elif x > 21.11: 
        Nov_score.append(float('4'))
    elif x > 15.55:
        Nov_score.append(float('3'))
    elif x > 12.7:
        Nov_score.append(float('2'))
    else:
        Nov_score.append(float('1'))
city["nov_score_temp"]=Nov_score

# For December
Dec_score = []

for x in temp['Dec']:
    if x > 26.667:
        Dec_score.append(float('6'))
    elif x > 23.888:
        Dec_score.append(float('5'))
    elif x > 21.11: 
        Dec_score.append(float('4'))
    elif x > 15.55:
        Dec_score.append(float('3'))
    elif x > 12.7:
        Dec_score.append(float('2'))
    else:
        Dec_score.append(float('1'))
city["dec_score_temp"]=Dec_score

In [6]:
city_final['Jan_total_score']=city['jan_score_temp']
city_final['Feb_total_score']=city['feb_score_temp']
city_final['Mar_total_score']=city['mar_score_temp'] 
city_final['Apr_total_score']=city['apr_score_temp'] 
city_final['May_total_score']=city['may_score_temp'] 
city_final['Jun_total_score']=city['jun_score_temp']
city_final['Jul_total_score']=city['jul_score_temp'] 
city_final['Aug_total_score']=city['aug_score_temp']
city_final['Sep_total_score']=city['sep_score_temp']
city_final['Oct_total_score']=city['oct_score_temp']
city_final['Nov_total_score']=city['nov_score_temp']
city_final['Dec_total_score']=city['dec_score_temp']

In [7]:
city_final

,City,Country,Latitude,Longitude,Jan_total_score,Feb_total_score,Mar_total_score,Apr_total_score,May_total_score,Jun_total_score,Jul_total_score,Aug_total_score,Sep_total_score,Oct_total_score,Nov_total_score,Dec_total_score
0,Vancouver,Canada,49.249660,-123.119339,1.0,1.0,1.0,1.0,2.0,3.0,3.0,3.0,2.0,1.0,1.0,1.0
1,Portland,United States,45.523449,-122.676208,1.0,1.0,1.0,1.0,2.0,3.0,3.0,3.0,3.0,1.0,1.0,1.0
2,San Francisco,United States,37.774929,-122.419418,1.0,1.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,1.0
3,Seattle,United States,47.606209,-122.332069,1.0,1.0,1.0,1.0,2.0,3.0,3.0,3.0,3.0,1.0,1.0,1.0
4,Los Angeles,United States,34.052231,-118.243683,1.0,2.0,2.0,3.0,3.0,3.0,4.0,4.0,4.0,3.0,2.0,1.0
5,San Diego,United States,32.715328,-117.157257,1.0,2.0,2.0,3.0,3.0,3.0,4.0,4.0,4.0,3.0,2.0,1.0
6,Las Vegas,United States,36.174969,-115.137222,1.0,1.0,3.0,3.0,4.0,6.0,6.0,6.0,5.0,3.0,1.0,1.0
7,Phoenix,United States,33.448380,-112.074043,1.0,2.0,3.0,4.0,5.0,6.0,6.0,6.0,6.0,4.0,3.0,1.0
8,Albuquerque,United States,35.084492,-106.651138,1.0,1.0,1.0,1.0,3.0,4.0,4.0,3.0,3.0,1.0,1.0,1.0
9,Denver,United States,39.739151,-104.984703,1.0,1.0,1.0,1.0,1.0,3.0,4.0,3.0,3.0,1.0,1.0,1.0
10,San Antonio,United States,29.424120,-98.493629,1.0,2.0,3.0,3.0,4.0,6.0,6.0,6.0,5.0,4.0,3.0,1.0
11,Dallas,United States,32.783058,-96.806671,1.0,1.0,2.0,3.0,4.0,6.0,6.0,6.0,5.0,3.0,2.0,1.0
12,Houston,United States,29.763281,-95.363274,1.0,2.0,3.0,3.0,4.0,6.0,6.0,6.0,5.0,4.0,3.0,2.0
13,Kansas City,United States,39.099731,-94.578568,1.0,1.0,1.0,2.0,3.0,5.0,5.0,5.0,4.0,2.0,1.0,1.0
14,Minneapolis,United States,44.979969,-93.263840,1.0,1.0,1.0,1.0,2.0,3.0,4.0,3.0,3.0,1.0,1.0,1.0
15,Saint Louis,United States,38.627270,-90.197891,1.0,1.0,1.0,2.0,3.0,5.0,5.0,5.0,4.0,2.0,1.0,1.0
16,Chicago,United States,41.850029,-87.650047,1.0,1.0,1.0,1.0,2.0,3.0,4.0,4.0,3.0,2.0,1.0,1.0
17,Nashville,United States,36.165890,-86.784439,1.0,1.0,1.0,3.0,3.0,5.0,5.0,5.0,4.0,3.0,1.0,1.0
18,Indianapolis,United States,39.768379,-86.158043,1.0,1.0,1.0,1.0,3.0,4.0,4.0,4.0,3.0,2.0,1.0,1.0
19,Atlanta,United States,33.749001,-84.387978,1.0,1.0,1.0,3.0,3.0,5.0,5.0,5.0,4.0,3.0,1.0,1.0
20,Detroit,United States,42.331429,-83.045753,1.0,1.0,1.0,1.0,2.0,3.0,4.0,4.0,3.0,1.0,1.0,1.0
21,Jacksonville,United States,30.332180,-81.655647,2.0,2.0,3.0,4.0,4.0,6.0,6.0,6.0,5.0,4.0,3.0,3.0
22,Charlotte,United States,35.227089,-80.843132,1.0,1.0,1.0,3.0,3.0,5.0,5.0,5.0,4.0,3.0,1.0,1.0
23,Miami,United States,25.774269,-80.193657,3.0,4.0,4.0,5.0,5.0,6.0,6.0,6.0,6.0,5.0,4.0,4.0
24,Pittsburgh,United States,40.440620,-79.995888,1.0,1.0,1.0,1.0,3.0,3.0,4.0,4.0,3.0,1.0,1.0,1.0
25,Toronto,Canada,43.700111,-79.416298,1.0,1.0,1.0,1.0,2.0,3.0,4.0,3.0,3.0,1.0,1.0,1.0
26,Philadelphia,United States,39.952339,-75.163788,1.0,1.0,1.0,1.0,3.0,4.0,5.0,4.0,3.0,2.0,1.0,1.0
27,New York,United States,40.714272,-74.005966,1.0,1.0,1.0,1.0,3.0,4.0,5.0,4.0,3.0,2.0,1.0,1.0
28,Montreal,Canada,45.508839,-73.587807,1.0,1.0,1.0,1.0,2.0,3.0,4.0,3.0,3.0,1.0,1.0,1.0
29,Boston,United States,42.358429,-71.059769,1.0,1.0,1.0,1.0,2.0,3.0,4.0,4.0,3.0,2.0,1.0,1.0
30,Beersheba,Israel,31.251810,34.791302,1.0,1.0,2.0,3.0,4.0,4.0,5.0,5.0,4.0,3.0,2.0,1.0
31,Tel Aviv District,Israel,32.083328,34.799999,2.0,2.0,3.0,3.0,4.0,5.0,6.0,6.0,6.0,4.0,3.0,2.0
32,Eilat,Israel,29.558050,34.948212,2.0,2.0,3.0,4.0,6.0,6.0,6.0,6.0,6.0,5.0,3.0,2.0
33,Haifa,Israel,32.815559,34.989170,2.0,3.0,3.0,3.0,4.0,5.0,6.0,6.0,6.0,5.0,3.0,3.0
34,Nahariyya,Israel,33.005859,35.094090,2.0,2.0,3.0,3.0,4.0,5.0,6.0,6.0,5.0,4.0,3.0,2.0
35,Jerusalem,Israel,31.769039,35.216331,1.0,2.0,3.0,3.0,4.0,5.0,5.0,6.0,5.0,4.0,3.0,2.0

#convert cell to code if rain is applicable
#scoring for rain
Jan_score=[]

for x in rain['Jan']:
    if x > .222:
        Jan_score.append(float('.5')),    
    elif x > .184:
        Jan_score.append(float('1')),
    elif x > .149:
        Jan_score.append(float('1.5')), 
    elif x > .117:
        Jan_score.append(float('2')),
    elif x > .0622:
        Jan_score.append(float('2.5')), 
    else:
        Jan_score.append(float('3')),
city["jan_score_rain"]=Jan_score

Feb_score=[]

for x in rain['Feb']:
    if x > .222:
        Feb_score.append(float('.5')),    
    elif x > .184:
        Feb_score.append(float('1')),
    elif x > .149:
        Feb_score.append(float('1.5')), 
    elif x > .117:
        Feb_score.append(float('2')),
    elif x > .0622:
        Feb_score.append(float('2.5')), 
    else:
        Feb_score.append(float('3')),

city["feb_score_rain"]=Feb_score

Mar_score=[]
for x in rain['Mar']:
    if x > .222:
        Mar_score.append(float('.5')),    
    elif x > .184:
        Mar_score.append(float('1')),
    elif x > .149:
        Mar_score.append(float('1.5')), 
    elif x > .117:
        Mar_score.append(float('2')),
    elif x > .0622:
        Mar_score.append(float('2.5')), 
    else:
        Mar_score.append(float('3')),
city["mar_score_rain"]=Mar_score

Apr_score=[]
for x in rain['Apr']:
    if x > .222:
        Apr_score.append(float('.5')),    
    elif x > .184:
        Apr_score.append(float('1')),
    elif x > .149:
        Apr_score.append(float('1.5')), 
    elif x > .117:
        Apr_score.append(float('2')),
    elif x > .0622:
        Apr_score.append(float('2.5')), 
    else:
        Apr_score.append(float('3')),
city["apr_score_rain"]=Apr_score

May_score=[]
for x in rain['May']:
    if x > .222:
        May_score.append(float('.5')),    
    elif x > .184:
        May_score.append(float('1')),
    elif x > .149:
        May_score.append(float('1.5')), 
    elif x > .117:
        May_score.append(float('2')),
    elif x > .0622:
        May_score.append(float('2.5')), 
    else:
        May_score.append(float('3')),
city["may_score_rain"]=May_score

Jun_score=[]
for x in rain['Jun']:
    if x > .222:
        Jun_score.append(float('.5')),    
    elif x > .184:
        Jun_score.append(float('1')),
    elif x > .149:
        Jun_score.append(float('1.5')), 
    elif x > .117:
        Jun_score.append(float('2')),
    elif x > .0622:
        Jun_score.append(float('2.5')), 
    else:
        Jun_score.append(float('3')),
city["jun_score_rain"]=Jun_score

Jul_score=[]
for x in rain['Jul']:
    if x > .222:
        Jul_score.append(float('.5')),    
    elif x > .184:
        Jul_score.append(float('1')),
    elif x > .149:
        Jul_score.append(float('1.5')), 
    elif x > .117:
        Jul_score.append(float('2')),
    elif x > .0622:
        Jul_score.append(float('2.5')), 
    else:
        Jul_score.append(float('3')),
city["jul_score_rain"]=Jul_score

Aug_score=[]
for x in rain['Aug']:
    if x > .222:
        Aug_score.append(float('.5')),    
    elif x > .184:
        Aug_score.append(float('1')),
    elif x > .149:
        Aug_score.append(float('1.5')), 
    elif x > .117:
        Aug_score.append(float('2')),
    elif x > .0622:
        Aug_score.append(float('2.5')), 
    else:
        Aug_score.append(float('3')),
city["aug_score_rain"]=Aug_score

Sep_score=[]
for x in rain['Sep']:
    if x > .222:
        Sep_score.append(float('.5')),    
    elif x > .184:
        Sep_score.append(float('1')),
    elif x > .149:
        Sep_score.append(float('1.5')), 
    elif x > .117:
        Sep_score.append(float('2')),
    elif x > .0622:
        Sep_score.append(float('2.5')), 
    else:
        Sep_score.append(float('3')),
city["sep_score_rain"]=Sep_score

Oct_score=[]
for x in rain['Oct']:
    if x > .222:
        Oct_score.append(float('.5')),    
    elif x > .184:
        Oct_score.append(float('1')),
    elif x > .149:
        Oct_score.append(float('1.5')), 
    elif x > .117:
        Oct_score.append(float('2')),
    elif x > .0622:
        Oct_score.append(float('2.5')), 
    else:
        Oct_score.append(float('3')),
city["oct_score_rain"]=Oct_score

Nov_score=[]
for x in rain['Nov']:
    if x > .222:
        Nov_score.append(float('.5')),    
    elif x > .184:
        Nov_score.append(float('1')),
    elif x > .149:
        Nov_score.append(float('1.5')), 
    elif x > .117:
        Nov_score.append(float('2')),
    elif x > .0622:
        Nov_score.append(float('2.5')), 
    else:
        Nov_score.append(float('3')),
city["nov_score_rain"]=Nov_score


Dec_score=[]
for x in rain['Dec']:
    if x > .222:
        Dec_score.append(float('.5')),    
    elif x > .184:
        Dec_score.append(float('1')),
    elif x > .149:
        Dec_score.append(float('1.5')), 
    elif x > .117:
        Dec_score.append(float('2')),
    elif x > .0622:
        Dec_score.append(float('2.5')), 
    else:
        Dec_score.append(float('3')),
city["dec_score_rain"]=Dec_score

#convert cell to code 
city_final['Jan_total_score']=city['jan_score_temp'] + city['jan_score_wind']+city['jan_score_rain']
city_final['Feb_total_score']=city['feb_score_temp'] + city['feb_score_wind']+city['feb_score_rain']
city_final['Mar_total_score']=city['mar_score_temp'] + city['mar_score_wind']+city['mar_score_rain']
city_final['Apr_total_score']=city['apr_score_temp'] + city['apr_score_wind']+city['apr_score_rain']
city_final['May_total_score']=city['may_score_temp'] + city['may_score_wind']+city['may_score_rain']
city_final['Jun_total_score']=city['jun_score_temp'] + city['jun_score_wind']+city['jun_score_rain']
city_final['Jul_total_score']=city['jul_score_temp'] + city['jul_score_wind']+city['jul_score_rain']
city_final['Aug_total_score']=city['aug_score_temp'] + city['aug_score_wind']+city['aug_score_rain']
city_final['Sep_total_score']=city['sep_score_temp'] + city['sep_score_wind']+city['sep_score_rain']
city_final['Oct_total_score']=city['oct_score_temp'] + city['oct_score_wind']+city['oct_score_rain']
city_final['Nov_total_score']=city['nov_score_temp'] + city['nov_score_wind']+city['nov_score_rain']
city_final['Dec_total_score']=city['dec_score_temp'] + city['dec_score_wind']+city['dec_score_rain']

In [8]:
cd ../Score_Datasets/

/Users/alexandersu/Documents/Vemgoo/vmg-prelim/Score_Datasets

In [ ]:
city_final.to_csv("sportname_final_score.csv", index=False)