In [4]:
import numpy as np
import pandas as pd

In [5]:
cd historical-hourly-weather-data/

/Users/alexandersu/Documents/Vemgoo/In_Progress/historical-hourly-weather-data

In [6]:
wind=pd.read_csv('wind_speed.csv')
wind=pd.DataFrame(wind)
wind
df2=pd.read_csv('city_attributes.csv')
df2

                 City        Country   Latitude   Longitude
0           Vancouver         Canada  49.249660 -123.119339
1            Portland  United States  45.523449 -122.676208
2       San Francisco  United States  37.774929 -122.419418
3             Seattle  United States  47.606209 -122.332069
4         Los Angeles  United States  34.052231 -118.243683
5           San Diego  United States  32.715328 -117.157257
6           Las Vegas  United States  36.174969 -115.137222
7             Phoenix  United States  33.448380 -112.074043
8         Albuquerque  United States  35.084492 -106.651138
9              Denver  United States  39.739151 -104.984703
10        San Antonio  United States  29.424120  -98.493629
11             Dallas  United States  32.783058  -96.806671
12            Houston  United States  29.763281  -95.363274
13        Kansas City  United States  39.099731  -94.578568
14        Minneapolis  United States  44.979969  -93.263840
15        Saint Louis  United States  38.627270  -90.197891
16            Chicago  United States  41.850029  -87.650047
17          Nashville  United States  36.165890  -86.784439
18       Indianapolis  United States  39.768379  -86.158043
19            Atlanta  United States  33.749001  -84.387978
20            Detroit  United States  42.331429  -83.045753
21       Jacksonville  United States  30.332180  -81.655647
22          Charlotte  United States  35.227089  -80.843132
23              Miami  United States  25.774269  -80.193657
24         Pittsburgh  United States  40.440620  -79.995888
25            Toronto         Canada  43.700111  -79.416298
26       Philadelphia  United States  39.952339  -75.163788
27           New York  United States  40.714272  -74.005966
28           Montreal         Canada  45.508839  -73.587807
29             Boston  United States  42.358429  -71.059769
30          Beersheba         Israel  31.251810   34.791302
31  Tel Aviv District         Israel  32.083328   34.799999
32              Eilat         Israel  29.558050   34.948212
33              Haifa         Israel  32.815559   34.989170
34          Nahariyya         Israel  33.005859   35.094090
35          Jerusalem         Israel  31.769039   35.216331

In [7]:
wind.shape

(45253, 37)

In [9]:
Jan=wind[wind['datetime'].str.contains("-01-")]
Feb=wind[wind['datetime'].str.contains("-02-")]
Mar=wind[wind['datetime'].str.contains("-03-")]
Apr=wind[wind['datetime'].str.contains("-04-")]
May=wind[wind['datetime'].str.contains("-05-")]
Jun=wind[wind['datetime'].str.contains("-06-")]
Jul=wind[wind['datetime'].str.contains("-07-")]
Aug=wind[wind['datetime'].str.contains("-08-")]
Sep=wind[wind['datetime'].str.contains("-09-")]
Oct=wind[wind['datetime'].str.contains("-10-")]
Nov=wind[wind['datetime'].str.contains("-11-")]
Dec=wind[wind['datetime'].str.contains("-12-")]

In [10]:
Jan_mean=Jan.mean()
Feb_mean=Feb.mean()
Mar_mean=Mar.mean()
Apr_mean=Apr.mean()
May_mean=May.mean()
Jun_mean=Jun.mean()
Jul_mean=Jul.mean()
Aug_mean=Aug.mean()
Sep_mean=Sep.mean()
Oct_mean=Oct.mean()
Nov_mean=Nov.mean()
Dec_mean=Dec.mean()

In [11]:
Jan.dtypes

datetime              object
Vancouver            float64
Portland             float64
San Francisco        float64
Seattle              float64
Los Angeles          float64
San Diego            float64
Las Vegas            float64
Phoenix              float64
Albuquerque          float64
Denver               float64
San Antonio          float64
Dallas               float64
Houston              float64
Kansas City          float64
Minneapolis          float64
Saint Louis          float64
Chicago              float64
Nashville            float64
Indianapolis         float64
Atlanta              float64
Detroit              float64
Jacksonville         float64
Charlotte            float64
Miami                float64
Pittsburgh           float64
Toronto              float64
Philadelphia         float64
New York             float64
Montreal             float64
Boston               float64
Beersheba            float64
Tel Aviv District    float64
Eilat                float64
Haifa                float64
Nahariyya            float64
Jerusalem            float64
dtype: object

In [12]:
Jan.mean()

Vancouver            1.930376
Portland             2.172312
San Francisco        2.350000
Seattle              1.712903
Los Angeles          1.104570
San Diego            1.447581
Las Vegas            2.164336
Phoenix              1.655645
Albuquerque          2.456452
Denver               2.304301
San Antonio          2.754570
Dallas               3.400806
Houston              2.948656
Kansas City          3.343548
Minneapolis          3.201882
Saint Louis          3.378226
Chicago              4.158065
Nashville            2.686290
Indianapolis         3.644086
Atlanta              2.272849
Detroit              3.457527
Jacksonville         2.883602
Charlotte            2.376882
Miami                3.090860
Pittsburgh           3.012634
Toronto              4.968548
Philadelphia         2.784409
New York             3.490054
Montreal             4.108871
Boston               3.676882
Beersheba            2.019086
Tel Aviv District    2.846505
Eilat                2.755376
Haifa                4.046774
Nahariyya            3.490860
Jerusalem            2.061828
dtype: float64

In [13]:
Janpd=pd.DataFrame(Jan_mean)
Febpd=pd.DataFrame(Feb_mean)
Marpd=pd.DataFrame(Mar_mean)
Aprpd=pd.DataFrame(Apr_mean)
Maypd=pd.DataFrame(May_mean)
Junpd=pd.DataFrame(Jun_mean)
Julpd=pd.DataFrame(Jul_mean)
Augpd=pd.DataFrame(Aug_mean)
Seppd=pd.DataFrame(Sep_mean)
Octpd=pd.DataFrame(Oct_mean)
Novpd=pd.DataFrame(Nov_mean)
Decpd=pd.DataFrame(Dec_mean)

In [14]:
full_table = pd.concat([Janpd, Febpd, Marpd, Aprpd, Maypd
                       ,Junpd,Julpd,Augpd,Seppd, Octpd, Novpd,Decpd ], axis=1, sort=False)

In [15]:
full_table

,0,0,0,0,0,0,0,0,0,0,0,0
Vancouver,1.930376,2.391548,2.694355,2.589722,1.994086,2.113611,2.557258,2.558483,2.507363,2.423554,2.754444,2.683602
Portland,2.172312,2.510047,2.327688,2.070556,1.748118,1.436944,2.104301,1.695699,1.668611,1.781173,2.653014,2.409946
San Francisco,2.350000,3.190603,3.139516,3.814722,3.398925,2.238611,2.827911,2.554570,2.623333,2.295684,2.327222,2.795161
Seattle,1.712903,2.348109,2.454570,2.310278,1.915860,1.745833,2.068548,1.829032,2.049444,2.141092,2.410519,2.394086
Los Angeles,1.104570,0.959515,1.257258,1.464444,1.515591,1.189444,1.659677,1.319086,1.256111,0.873736,1.015360,1.104032
San Diego,1.447581,1.746749,1.835753,2.251389,2.105914,1.560833,1.972043,1.678226,1.818056,1.510222,1.612986,1.558333
Las Vegas,2.164336,2.248522,2.722431,3.243401,3.177294,2.345833,2.955621,2.230645,2.262778,2.020013,2.177333,2.141129
Phoenix,1.655645,1.617317,1.748319,2.275278,2.158871,2.014722,2.555108,2.049731,2.027500,1.665918,1.674424,1.542742
Albuquerque,2.456452,2.884752,3.233791,3.775000,3.216667,2.630833,2.910484,2.365323,2.568889,2.259942,2.614848,2.402688
Denver,2.304301,3.267730,3.150578,3.101944,2.310484,1.816389,2.202688,2.042204,2.239167,2.171871,2.394927,2.394892
San Antonio,2.754570,3.230496,3.371505,3.428333,3.680914,2.929167,3.300269,2.979570,2.629167,2.824084,2.653945,2.596774
Dallas,3.400806,4.135934,4.054032,4.511944,3.992742,3.493889,3.554032,2.937634,3.084444,3.564368,3.562020,3.367034
Houston,2.948656,3.519208,3.625538,3.621111,3.396774,2.623611,2.600538,2.501882,2.291667,2.655955,2.949953,2.917204
Kansas City,3.343548,3.771572,3.929032,4.008333,3.334946,3.302778,3.243011,2.773387,3.103889,3.557852,3.765883,2.992742
Minneapolis,3.201882,3.735520,3.732527,4.225833,3.551613,3.090000,3.022312,2.631791,3.189444,3.562795,3.502909,3.129032
Saint Louis,3.378226,3.817671,3.708871,3.625833,2.904032,2.480000,2.437903,2.199462,2.453889,3.338351,3.220154,2.980914
Chicago,4.158065,4.612884,4.199194,4.181111,3.399462,2.807778,3.194624,2.808602,3.257500,4.132779,4.258087,3.994892
Nashville,2.686290,3.069740,3.110484,3.045556,2.302688,1.845790,1.937366,1.764991,1.827222,2.272298,2.582499,2.688710
Indianapolis,3.644086,3.978132,4.033602,4.017778,3.294624,2.641389,2.723387,2.163978,2.280833,3.237475,3.372818,3.335215
Atlanta,2.272849,2.734043,2.754839,2.581667,2.186559,1.935278,1.944086,1.855376,1.902500,2.107841,2.363044,2.168011
Detroit,3.457527,3.559693,3.452957,3.518056,3.144892,2.773056,2.637903,2.422849,2.613889,3.449337,3.593205,3.251344
Jacksonville,2.883602,3.175827,3.173925,3.228889,2.872043,2.330000,2.750538,2.519624,2.513889,2.899573,3.056086,2.546237
Charlotte,2.376882,2.869385,2.764785,2.853889,2.352419,1.957766,2.069892,2.009409,2.286944,2.573804,2.382360,2.086559
Miami,3.090860,3.429669,3.413710,3.673056,3.344086,2.944722,2.969355,2.829032,2.877778,3.665365,3.578611,2.970161
Pittsburgh,3.012634,3.197695,3.197581,3.103333,2.493280,1.857222,2.016667,1.613441,1.731667,2.363064,2.716314,2.866129
Toronto,4.968548,5.229314,4.393548,4.449167,3.202151,2.688333,2.933333,2.739785,2.816111,3.926758,4.217594,4.402419
Philadelphia,2.784409,3.268913,3.306720,3.127778,2.580645,2.130000,2.421619,1.985484,2.199722,2.644574,2.770305,2.519624
New York,3.490054,3.764480,4.011022,3.881389,2.676613,2.323056,2.590323,2.552419,2.742222,3.221993,3.849444,3.475000
Montreal,4.108871,4.195035,4.203226,4.378889,3.959946,3.073333,3.445968,3.271237,3.304167,3.756010,4.104724,4.162903
Boston,3.676882,4.151596,4.204839,4.007778,3.173925,2.810556,2.839247,2.540054,3.002222,3.523703,3.512916,3.137634
Beersheba,2.019086,1.997340,2.245699,2.201667,2.146774,2.125000,2.123387,2.056183,1.980000,1.626033,1.764722,1.652688
Tel Aviv District,2.846505,2.637707,2.976613,2.908889,2.844851,2.529722,2.786290,2.829839,2.736944,2.426997,2.495000,2.684140
Eilat,2.755376,2.555260,2.850806,2.957222,3.543280,4.052500,4.610484,4.270430,4.311111,3.428735,3.064167,2.973118
Haifa,4.046774,3.937648,4.083625,3.565000,3.114247,2.826944,2.914516,2.710215,2.860833,2.917126,3.423333,3.299005
Nahariyya,3.490860,3.205083,3.684593,3.103333,2.542742,2.614444,2.863978,2.668548,2.761111,2.842287,3.378333,3.176075
Jerusalem,2.061828,2.054669,2.108065,2.087222,2.006722,1.634444,2.017204,1.896505,1.754444,1.405877,1.760278,1.861022

In [16]:
full_table.columns=['Jan','Feb','Mar','Apr','May','Jun','Jul'
                   ,'Aug', 'Sep','Oct','Nov','Dec']

In [17]:
full_table

,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
Vancouver,1.930376,2.391548,2.694355,2.589722,1.994086,2.113611,2.557258,2.558483,2.507363,2.423554,2.754444,2.683602
Portland,2.172312,2.510047,2.327688,2.070556,1.748118,1.436944,2.104301,1.695699,1.668611,1.781173,2.653014,2.409946
San Francisco,2.350000,3.190603,3.139516,3.814722,3.398925,2.238611,2.827911,2.554570,2.623333,2.295684,2.327222,2.795161
Seattle,1.712903,2.348109,2.454570,2.310278,1.915860,1.745833,2.068548,1.829032,2.049444,2.141092,2.410519,2.394086
Los Angeles,1.104570,0.959515,1.257258,1.464444,1.515591,1.189444,1.659677,1.319086,1.256111,0.873736,1.015360,1.104032
San Diego,1.447581,1.746749,1.835753,2.251389,2.105914,1.560833,1.972043,1.678226,1.818056,1.510222,1.612986,1.558333
Las Vegas,2.164336,2.248522,2.722431,3.243401,3.177294,2.345833,2.955621,2.230645,2.262778,2.020013,2.177333,2.141129
Phoenix,1.655645,1.617317,1.748319,2.275278,2.158871,2.014722,2.555108,2.049731,2.027500,1.665918,1.674424,1.542742
Albuquerque,2.456452,2.884752,3.233791,3.775000,3.216667,2.630833,2.910484,2.365323,2.568889,2.259942,2.614848,2.402688
Denver,2.304301,3.267730,3.150578,3.101944,2.310484,1.816389,2.202688,2.042204,2.239167,2.171871,2.394927,2.394892
San Antonio,2.754570,3.230496,3.371505,3.428333,3.680914,2.929167,3.300269,2.979570,2.629167,2.824084,2.653945,2.596774
Dallas,3.400806,4.135934,4.054032,4.511944,3.992742,3.493889,3.554032,2.937634,3.084444,3.564368,3.562020,3.367034
Houston,2.948656,3.519208,3.625538,3.621111,3.396774,2.623611,2.600538,2.501882,2.291667,2.655955,2.949953,2.917204
Kansas City,3.343548,3.771572,3.929032,4.008333,3.334946,3.302778,3.243011,2.773387,3.103889,3.557852,3.765883,2.992742
Minneapolis,3.201882,3.735520,3.732527,4.225833,3.551613,3.090000,3.022312,2.631791,3.189444,3.562795,3.502909,3.129032
Saint Louis,3.378226,3.817671,3.708871,3.625833,2.904032,2.480000,2.437903,2.199462,2.453889,3.338351,3.220154,2.980914
Chicago,4.158065,4.612884,4.199194,4.181111,3.399462,2.807778,3.194624,2.808602,3.257500,4.132779,4.258087,3.994892
Nashville,2.686290,3.069740,3.110484,3.045556,2.302688,1.845790,1.937366,1.764991,1.827222,2.272298,2.582499,2.688710
Indianapolis,3.644086,3.978132,4.033602,4.017778,3.294624,2.641389,2.723387,2.163978,2.280833,3.237475,3.372818,3.335215
Atlanta,2.272849,2.734043,2.754839,2.581667,2.186559,1.935278,1.944086,1.855376,1.902500,2.107841,2.363044,2.168011
Detroit,3.457527,3.559693,3.452957,3.518056,3.144892,2.773056,2.637903,2.422849,2.613889,3.449337,3.593205,3.251344
Jacksonville,2.883602,3.175827,3.173925,3.228889,2.872043,2.330000,2.750538,2.519624,2.513889,2.899573,3.056086,2.546237
Charlotte,2.376882,2.869385,2.764785,2.853889,2.352419,1.957766,2.069892,2.009409,2.286944,2.573804,2.382360,2.086559
Miami,3.090860,3.429669,3.413710,3.673056,3.344086,2.944722,2.969355,2.829032,2.877778,3.665365,3.578611,2.970161
Pittsburgh,3.012634,3.197695,3.197581,3.103333,2.493280,1.857222,2.016667,1.613441,1.731667,2.363064,2.716314,2.866129
Toronto,4.968548,5.229314,4.393548,4.449167,3.202151,2.688333,2.933333,2.739785,2.816111,3.926758,4.217594,4.402419
Philadelphia,2.784409,3.268913,3.306720,3.127778,2.580645,2.130000,2.421619,1.985484,2.199722,2.644574,2.770305,2.519624
New York,3.490054,3.764480,4.011022,3.881389,2.676613,2.323056,2.590323,2.552419,2.742222,3.221993,3.849444,3.475000
Montreal,4.108871,4.195035,4.203226,4.378889,3.959946,3.073333,3.445968,3.271237,3.304167,3.756010,4.104724,4.162903
Boston,3.676882,4.151596,4.204839,4.007778,3.173925,2.810556,2.839247,2.540054,3.002222,3.523703,3.512916,3.137634
Beersheba,2.019086,1.997340,2.245699,2.201667,2.146774,2.125000,2.123387,2.056183,1.980000,1.626033,1.764722,1.652688
Tel Aviv District,2.846505,2.637707,2.976613,2.908889,2.844851,2.529722,2.786290,2.829839,2.736944,2.426997,2.495000,2.684140
Eilat,2.755376,2.555260,2.850806,2.957222,3.543280,4.052500,4.610484,4.270430,4.311111,3.428735,3.064167,2.973118
Haifa,4.046774,3.937648,4.083625,3.565000,3.114247,2.826944,2.914516,2.710215,2.860833,2.917126,3.423333,3.299005
Nahariyya,3.490860,3.205083,3.684593,3.103333,2.542742,2.614444,2.863978,2.668548,2.761111,2.842287,3.378333,3.176075
Jerusalem,2.061828,2.054669,2.108065,2.087222,2.006722,1.634444,2.017204,1.896505,1.754444,1.405877,1.760278,1.861022

In [18]:
full_table.index.names = ['City']
full_table

,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
City,,,,,,,,,,,,
Vancouver,1.930376,2.391548,2.694355,2.589722,1.994086,2.113611,2.557258,2.558483,2.507363,2.423554,2.754444,2.683602
Portland,2.172312,2.510047,2.327688,2.070556,1.748118,1.436944,2.104301,1.695699,1.668611,1.781173,2.653014,2.409946
San Francisco,2.350000,3.190603,3.139516,3.814722,3.398925,2.238611,2.827911,2.554570,2.623333,2.295684,2.327222,2.795161
Seattle,1.712903,2.348109,2.454570,2.310278,1.915860,1.745833,2.068548,1.829032,2.049444,2.141092,2.410519,2.394086
Los Angeles,1.104570,0.959515,1.257258,1.464444,1.515591,1.189444,1.659677,1.319086,1.256111,0.873736,1.015360,1.104032
San Diego,1.447581,1.746749,1.835753,2.251389,2.105914,1.560833,1.972043,1.678226,1.818056,1.510222,1.612986,1.558333
Las Vegas,2.164336,2.248522,2.722431,3.243401,3.177294,2.345833,2.955621,2.230645,2.262778,2.020013,2.177333,2.141129
Phoenix,1.655645,1.617317,1.748319,2.275278,2.158871,2.014722,2.555108,2.049731,2.027500,1.665918,1.674424,1.542742
Albuquerque,2.456452,2.884752,3.233791,3.775000,3.216667,2.630833,2.910484,2.365323,2.568889,2.259942,2.614848,2.402688
Denver,2.304301,3.267730,3.150578,3.101944,2.310484,1.816389,2.202688,2.042204,2.239167,2.171871,2.394927,2.394892
San Antonio,2.754570,3.230496,3.371505,3.428333,3.680914,2.929167,3.300269,2.979570,2.629167,2.824084,2.653945,2.596774
Dallas,3.400806,4.135934,4.054032,4.511944,3.992742,3.493889,3.554032,2.937634,3.084444,3.564368,3.562020,3.367034
Houston,2.948656,3.519208,3.625538,3.621111,3.396774,2.623611,2.600538,2.501882,2.291667,2.655955,2.949953,2.917204
Kansas City,3.343548,3.771572,3.929032,4.008333,3.334946,3.302778,3.243011,2.773387,3.103889,3.557852,3.765883,2.992742
Minneapolis,3.201882,3.735520,3.732527,4.225833,3.551613,3.090000,3.022312,2.631791,3.189444,3.562795,3.502909,3.129032
Saint Louis,3.378226,3.817671,3.708871,3.625833,2.904032,2.480000,2.437903,2.199462,2.453889,3.338351,3.220154,2.980914
Chicago,4.158065,4.612884,4.199194,4.181111,3.399462,2.807778,3.194624,2.808602,3.257500,4.132779,4.258087,3.994892
Nashville,2.686290,3.069740,3.110484,3.045556,2.302688,1.845790,1.937366,1.764991,1.827222,2.272298,2.582499,2.688710
Indianapolis,3.644086,3.978132,4.033602,4.017778,3.294624,2.641389,2.723387,2.163978,2.280833,3.237475,3.372818,3.335215
Atlanta,2.272849,2.734043,2.754839,2.581667,2.186559,1.935278,1.944086,1.855376,1.902500,2.107841,2.363044,2.168011
Detroit,3.457527,3.559693,3.452957,3.518056,3.144892,2.773056,2.637903,2.422849,2.613889,3.449337,3.593205,3.251344
Jacksonville,2.883602,3.175827,3.173925,3.228889,2.872043,2.330000,2.750538,2.519624,2.513889,2.899573,3.056086,2.546237
Charlotte,2.376882,2.869385,2.764785,2.853889,2.352419,1.957766,2.069892,2.009409,2.286944,2.573804,2.382360,2.086559
Miami,3.090860,3.429669,3.413710,3.673056,3.344086,2.944722,2.969355,2.829032,2.877778,3.665365,3.578611,2.970161
Pittsburgh,3.012634,3.197695,3.197581,3.103333,2.493280,1.857222,2.016667,1.613441,1.731667,2.363064,2.716314,2.866129
Toronto,4.968548,5.229314,4.393548,4.449167,3.202151,2.688333,2.933333,2.739785,2.816111,3.926758,4.217594,4.402419
Philadelphia,2.784409,3.268913,3.306720,3.127778,2.580645,2.130000,2.421619,1.985484,2.199722,2.644574,2.770305,2.519624
New York,3.490054,3.764480,4.011022,3.881389,2.676613,2.323056,2.590323,2.552419,2.742222,3.221993,3.849444,3.475000
Montreal,4.108871,4.195035,4.203226,4.378889,3.959946,3.073333,3.445968,3.271237,3.304167,3.756010,4.104724,4.162903
Boston,3.676882,4.151596,4.204839,4.007778,3.173925,2.810556,2.839247,2.540054,3.002222,3.523703,3.512916,3.137634
Beersheba,2.019086,1.997340,2.245699,2.201667,2.146774,2.125000,2.123387,2.056183,1.980000,1.626033,1.764722,1.652688
Tel Aviv District,2.846505,2.637707,2.976613,2.908889,2.844851,2.529722,2.786290,2.829839,2.736944,2.426997,2.495000,2.684140
Eilat,2.755376,2.555260,2.850806,2.957222,3.543280,4.052500,4.610484,4.270430,4.311111,3.428735,3.064167,2.973118
Haifa,4.046774,3.937648,4.083625,3.565000,3.114247,2.826944,2.914516,2.710215,2.860833,2.917126,3.423333,3.299005
Nahariyya,3.490860,3.205083,3.684593,3.103333,2.542742,2.614444,2.863978,2.668548,2.761111,2.842287,3.378333,3.176075
Jerusalem,2.061828,2.054669,2.108065,2.087222,2.006722,1.634444,2.017204,1.896505,1.754444,1.405877,1.760278,1.861022

In [19]:
dest=pd.read_csv("city_attributes.csv")
dest

                 City        Country   Latitude   Longitude
0           Vancouver         Canada  49.249660 -123.119339
1            Portland  United States  45.523449 -122.676208
2       San Francisco  United States  37.774929 -122.419418
3             Seattle  United States  47.606209 -122.332069
4         Los Angeles  United States  34.052231 -118.243683
5           San Diego  United States  32.715328 -117.157257
6           Las Vegas  United States  36.174969 -115.137222
7             Phoenix  United States  33.448380 -112.074043
8         Albuquerque  United States  35.084492 -106.651138
9              Denver  United States  39.739151 -104.984703
10        San Antonio  United States  29.424120  -98.493629
11             Dallas  United States  32.783058  -96.806671
12            Houston  United States  29.763281  -95.363274
13        Kansas City  United States  39.099731  -94.578568
14        Minneapolis  United States  44.979969  -93.263840
15        Saint Louis  United States  38.627270  -90.197891
16            Chicago  United States  41.850029  -87.650047
17          Nashville  United States  36.165890  -86.784439
18       Indianapolis  United States  39.768379  -86.158043
19            Atlanta  United States  33.749001  -84.387978
20            Detroit  United States  42.331429  -83.045753
21       Jacksonville  United States  30.332180  -81.655647
22          Charlotte  United States  35.227089  -80.843132
23              Miami  United States  25.774269  -80.193657
24         Pittsburgh  United States  40.440620  -79.995888
25            Toronto         Canada  43.700111  -79.416298
26       Philadelphia  United States  39.952339  -75.163788
27           New York  United States  40.714272  -74.005966
28           Montreal         Canada  45.508839  -73.587807
29             Boston  United States  42.358429  -71.059769
30          Beersheba         Israel  31.251810   34.791302
31  Tel Aviv District         Israel  32.083328   34.799999
32              Eilat         Israel  29.558050   34.948212
33              Haifa         Israel  32.815559   34.989170
34          Nahariyya         Israel  33.005859   35.094090
35          Jerusalem         Israel  31.769039   35.216331

In [20]:
full_table_dest=(pd.merge(full_table, dest, on='City'))

In [21]:
full_table_dest

,City,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,Country,Latitude,Longitude
0,Vancouver,1.930376,2.391548,2.694355,2.589722,1.994086,2.113611,2.557258,2.558483,2.507363,2.423554,2.754444,2.683602,Canada,49.249660,-123.119339
1,Portland,2.172312,2.510047,2.327688,2.070556,1.748118,1.436944,2.104301,1.695699,1.668611,1.781173,2.653014,2.409946,United States,45.523449,-122.676208
2,San Francisco,2.350000,3.190603,3.139516,3.814722,3.398925,2.238611,2.827911,2.554570,2.623333,2.295684,2.327222,2.795161,United States,37.774929,-122.419418
3,Seattle,1.712903,2.348109,2.454570,2.310278,1.915860,1.745833,2.068548,1.829032,2.049444,2.141092,2.410519,2.394086,United States,47.606209,-122.332069
4,Los Angeles,1.104570,0.959515,1.257258,1.464444,1.515591,1.189444,1.659677,1.319086,1.256111,0.873736,1.015360,1.104032,United States,34.052231,-118.243683
5,San Diego,1.447581,1.746749,1.835753,2.251389,2.105914,1.560833,1.972043,1.678226,1.818056,1.510222,1.612986,1.558333,United States,32.715328,-117.157257
6,Las Vegas,2.164336,2.248522,2.722431,3.243401,3.177294,2.345833,2.955621,2.230645,2.262778,2.020013,2.177333,2.141129,United States,36.174969,-115.137222
7,Phoenix,1.655645,1.617317,1.748319,2.275278,2.158871,2.014722,2.555108,2.049731,2.027500,1.665918,1.674424,1.542742,United States,33.448380,-112.074043
8,Albuquerque,2.456452,2.884752,3.233791,3.775000,3.216667,2.630833,2.910484,2.365323,2.568889,2.259942,2.614848,2.402688,United States,35.084492,-106.651138
9,Denver,2.304301,3.267730,3.150578,3.101944,2.310484,1.816389,2.202688,2.042204,2.239167,2.171871,2.394927,2.394892,United States,39.739151,-104.984703
10,San Antonio,2.754570,3.230496,3.371505,3.428333,3.680914,2.929167,3.300269,2.979570,2.629167,2.824084,2.653945,2.596774,United States,29.424120,-98.493629
11,Dallas,3.400806,4.135934,4.054032,4.511944,3.992742,3.493889,3.554032,2.937634,3.084444,3.564368,3.562020,3.367034,United States,32.783058,-96.806671
12,Houston,2.948656,3.519208,3.625538,3.621111,3.396774,2.623611,2.600538,2.501882,2.291667,2.655955,2.949953,2.917204,United States,29.763281,-95.363274
13,Kansas City,3.343548,3.771572,3.929032,4.008333,3.334946,3.302778,3.243011,2.773387,3.103889,3.557852,3.765883,2.992742,United States,39.099731,-94.578568
14,Minneapolis,3.201882,3.735520,3.732527,4.225833,3.551613,3.090000,3.022312,2.631791,3.189444,3.562795,3.502909,3.129032,United States,44.979969,-93.263840
15,Saint Louis,3.378226,3.817671,3.708871,3.625833,2.904032,2.480000,2.437903,2.199462,2.453889,3.338351,3.220154,2.980914,United States,38.627270,-90.197891
16,Chicago,4.158065,4.612884,4.199194,4.181111,3.399462,2.807778,3.194624,2.808602,3.257500,4.132779,4.258087,3.994892,United States,41.850029,-87.650047
17,Nashville,2.686290,3.069740,3.110484,3.045556,2.302688,1.845790,1.937366,1.764991,1.827222,2.272298,2.582499,2.688710,United States,36.165890,-86.784439
18,Indianapolis,3.644086,3.978132,4.033602,4.017778,3.294624,2.641389,2.723387,2.163978,2.280833,3.237475,3.372818,3.335215,United States,39.768379,-86.158043
19,Atlanta,2.272849,2.734043,2.754839,2.581667,2.186559,1.935278,1.944086,1.855376,1.902500,2.107841,2.363044,2.168011,United States,33.749001,-84.387978
20,Detroit,3.457527,3.559693,3.452957,3.518056,3.144892,2.773056,2.637903,2.422849,2.613889,3.449337,3.593205,3.251344,United States,42.331429,-83.045753
21,Jacksonville,2.883602,3.175827,3.173925,3.228889,2.872043,2.330000,2.750538,2.519624,2.513889,2.899573,3.056086,2.546237,United States,30.332180,-81.655647
22,Charlotte,2.376882,2.869385,2.764785,2.853889,2.352419,1.957766,2.069892,2.009409,2.286944,2.573804,2.382360,2.086559,United States,35.227089,-80.843132
23,Miami,3.090860,3.429669,3.413710,3.673056,3.344086,2.944722,2.969355,2.829032,2.877778,3.665365,3.578611,2.970161,United States,25.774269,-80.193657
24,Pittsburgh,3.012634,3.197695,3.197581,3.103333,2.493280,1.857222,2.016667,1.613441,1.731667,2.363064,2.716314,2.866129,United States,40.440620,-79.995888
25,Toronto,4.968548,5.229314,4.393548,4.449167,3.202151,2.688333,2.933333,2.739785,2.816111,3.926758,4.217594,4.402419,Canada,43.700111,-79.416298
26,Philadelphia,2.784409,3.268913,3.306720,3.127778,2.580645,2.130000,2.421619,1.985484,2.199722,2.644574,2.770305,2.519624,United States,39.952339,-75.163788
27,New York,3.490054,3.764480,4.011022,3.881389,2.676613,2.323056,2.590323,2.552419,2.742222,3.221993,3.849444,3.475000,United States,40.714272,-74.005966
28,Montreal,4.108871,4.195035,4.203226,4.378889,3.959946,3.073333,3.445968,3.271237,3.304167,3.756010,4.104724,4.162903,Canada,45.508839,-73.587807
29,Boston,3.676882,4.151596,4.204839,4.007778,3.173925,2.810556,2.839247,2.540054,3.002222,3.523703,3.512916,3.137634,United States,42.358429,-71.059769
30,Beersheba,2.019086,1.997340,2.245699,2.201667,2.146774,2.125000,2.123387,2.056183,1.980000,1.626033,1.764722,1.652688,Israel,31.251810,34.791302
31,Tel Aviv District,2.846505,2.637707,2.976613,2.908889,2.844851,2.529722,2.786290,2.829839,2.736944,2.426997,2.495000,2.684140,Israel,32.083328,34.799999
32,Eilat,2.755376,2.555260,2.850806,2.957222,3.543280,4.052500,4.610484,4.270430,4.311111,3.428735,3.064167,2.973118,Israel,29.558050,34.948212
33,Haifa,4.046774,3.937648,4.083625,3.565000,3.114247,2.826944,2.914516,2.710215,2.860833,2.917126,3.423333,3.299005,Israel,32.815559,34.989170
34,Nahariyya,3.490860,3.205083,3.684593,3.103333,2.542742,2.614444,2.863978,2.668548,2.761111,2.842287,3.378333,3.176075,Israel,33.005859,35.094090
35,Jerusalem,2.061828,2.054669,2.108065,2.087222,2.006722,1.634444,2.017204,1.896505,1.754444,1.405877,1.760278,1.861022,Israel,31.769039,35.216331

In [22]:
full_table_dest.to_csv("wind_with_cord2.csv",index=False)

In [23]:
Jan.mean()

Vancouver            1.930376
Portland             2.172312
San Francisco        2.350000
Seattle              1.712903
Los Angeles          1.104570
San Diego            1.447581
Las Vegas            2.164336
Phoenix              1.655645
Albuquerque          2.456452
Denver               2.304301
San Antonio          2.754570
Dallas               3.400806
Houston              2.948656
Kansas City          3.343548
Minneapolis          3.201882
Saint Louis          3.378226
Chicago              4.158065
Nashville            2.686290
Indianapolis         3.644086
Atlanta              2.272849
Detroit              3.457527
Jacksonville         2.883602
Charlotte            2.376882
Miami                3.090860
Pittsburgh           3.012634
Toronto              4.968548
Philadelphia         2.784409
New York             3.490054
Montreal             4.108871
Boston               3.676882
Beersheba            2.019086
Tel Aviv District    2.846505
Eilat                2.755376
Haifa                4.046774
Nahariyya            3.490860
Jerusalem            2.061828
dtype: float64

In [24]:
pd.qcut(full_table_dest['Jan'],5)

0     (1.104, 2.164]
1     (2.164, 2.686]
2     (2.164, 2.686]
3     (1.104, 2.164]
4     (1.104, 2.164]
5     (1.104, 2.164]
6     (1.104, 2.164]
7     (1.104, 2.164]
8     (2.164, 2.686]
9     (2.164, 2.686]
10    (2.686, 3.013]
11     (3.013, 3.49]
12    (2.686, 3.013]
13     (3.013, 3.49]
14     (3.013, 3.49]
15     (3.013, 3.49]
16     (3.49, 4.969]
17    (2.164, 2.686]
18     (3.49, 4.969]
19    (2.164, 2.686]
20     (3.013, 3.49]
21    (2.686, 3.013]
22    (2.164, 2.686]
23     (3.013, 3.49]
24    (2.686, 3.013]
25     (3.49, 4.969]
26    (2.686, 3.013]
27     (3.013, 3.49]
28     (3.49, 4.969]
29     (3.49, 4.969]
30    (1.104, 2.164]
31    (2.686, 3.013]
32    (2.686, 3.013]
33     (3.49, 4.969]
34     (3.49, 4.969]
35    (1.104, 2.164]
Name: Jan, dtype: category
Categories (5, interval[float64]): [(1.104, 2.164] < (2.164, 2.686] < (2.686, 3.013] < (3.013, 3.49] < (3.49, 4.969]]

In [25]:
Jan_score=[]
for x in full_table_dest['Jan']:
    if x > 3.49:
        Jan_score.append(float('6')),    
    elif x > 3.013:
        Jan_score.append(float('5')),
    elif x > 2.686:
        Jan_score.append(float('4')), 
    elif x > 2.164:
        Jan_score.append(float('3')),
    elif x > 1.104:
        Jan_score.append(float('2')), 
    else:
        Jan_score.append(float('1')),
full_table_dest["Jan_score"]=Jan_score

In [26]:
Feb_score=[]

for x in full_table_dest['Feb']:
    if x > 3.49:
        Feb_score.append(float('6')),    
    elif x > 3.013:
        Feb_score.append(float('5')),
    elif x > 2.686:
        Feb_score.append(float('4')), 
    elif x > 2.164:
        Feb_score.append(float('3')),
    elif x > 1.104:
        Feb_score.append(float('2')), 
    else:
        Feb_score.append(float('1')),

full_table_dest["Feb_score"]=Feb_score

In [27]:
Mar_score=[]
for x in full_table_dest['Mar']:
    if x > 3.49:
        Mar_score.append(float('6')),    
    elif x > 3.013:
        Mar_score.append(float('5')),
    elif x > 2.686:
        Mar_score.append(float('4')), 
    elif x > 2.164:
        Mar_score.append(float('3')),
    elif x > 1.104:
        Mar_score.append(float('2')), 
    else:
        Mar_score.append(float('1')),
full_table_dest["Mar_score"]=Mar_score

In [28]:
Apr_score=[]
for x in full_table_dest['Apr']:
    if x > 3.49:
        Apr_score.append(float('6')),    
    elif x > 3.013:
        Apr_score.append(float('5')),
    elif x > 2.686:
        Apr_score.append(float('4')), 
    elif x > 2.164:
        Apr_score.append(float('3')),
    elif x > 1.104:
        Apr_score.append(float('2')), 
    else:
        Apr_score.append(float('1')),
full_table_dest["Apr_score"]=Apr_score

May_score=[]
for x in full_table_dest['May']:
    if x > 3.49:
        May_score.append(float('6')),    
    elif x > 3.013:
        May_score.append(float('5')),
    elif x > 2.686:
        May_score.append(float('4')), 
    elif x > 2.164:
        May_score.append(float('3')),
    elif x > 1.104:
        May_score.append(float('2')), 
    else:
        May_score.append(float('1')),
full_table_dest["May_score"]=May_score

Jun_score=[]
for x in full_table_dest['Jun']:
    if x > 3.49:
        Jun_score.append(float('6')),    
    elif x > 3.013:
        Jun_score.append(float('5')),
    elif x > 2.686:
        Jun_score.append(float('4')), 
    elif x > 2.164:
        Jun_score.append(float('3')),
    elif x > 1.104:
        Jun_score.append(float('2')), 
    else:
        Jun_score.append(float('1')),
full_table_dest["Jun_score"]=Jun_score

Jul_score=[]
for x in full_table_dest['Jul']:
    if x > 3.49:
        Jul_score.append(float('6')),    
    elif x > 3.013:
        Jul_score.append(float('5')),
    elif x > 2.686:
        Jul_score.append(float('4')), 
    elif x > 2.164:
        Jul_score.append(float('3')),
    elif x > 1.104:
        Jul_score.append(float('2')), 
    else:
        Jul_score.append(float('1')),
full_table_dest["Jul_score"]=Jul_score

Aug_score=[]
for x in full_table_dest['Aug']:
    if x > 3.49:
        Aug_score.append(float('6')),    
    elif x > 3.013:
        Aug_score.append(float('5')),
    elif x > 2.686:
        Aug_score.append(float('4')), 
    elif x > 2.164:
        Aug_score.append(float('3')),
    elif x > 1.104:
        Aug_score.append(float('2')), 
    else:
        Aug_score.append(float('1')),
full_table_dest["Aug_score"]=Aug_score

Sep_score=[]
for x in full_table_dest['Sep']:
    if x > 3.49:
        Sep_score.append(float('6')),    
    elif x > 3.013:
        Sep_score.append(float('5')),
    elif x > 2.686:
        Sep_score.append(float('4')), 
    elif x > 2.164:
        Sep_score.append(float('3')),
    elif x > 1.104:
        Sep_score.append(float('2')), 
    else:
        Sep_score.append(float('1')),
full_table_dest["Sep_score"]=Sep_score

Oct_score=[]
for x in full_table_dest['Oct']:
    if x > 3.49:
        Oct_score.append(float('6')),    
    elif x > 3.013:
        Oct_score.append(float('5')),
    elif x > 2.686:
        Oct_score.append(float('4')), 
    elif x > 2.164:
        Oct_score.append(float('3')),
    elif x > 1.104:
        Oct_score.append(float('2')), 
    else:
        Oct_score.append(float('1')),
full_table_dest["Oct_score"]=Oct_score

Nov_score=[]
for x in full_table_dest['Nov']:
    if x > 3.49:
        Nov_score.append(float('6')),    
    elif x > 3.013:
        Nov_score.append(float('5')),
    elif x > 2.686:
        Nov_score.append(float('4')), 
    elif x > 2.164:
        Nov_score.append(float('3')),
    elif x > 1.104:
        Nov_score.append(float('2')), 
    else:
        Nov_score.append(float('1')),
full_table_dest["Nov_score"]=Nov_score


Dec_score=[]
for x in full_table_dest['Dec']:
    if x > 3.49:
        Dec_score.append(float('6')),    
    elif x > 3.013:
        Dec_score.append(float('5')),
    elif x > 2.686:
        Dec_score.append(float('4')), 
    elif x > 2.164:
        Dec_score.append(float('3')),
    elif x > 1.104:
        Dec_score.append(float('2')), 
    else:
        Dec_score.append(float('1')),
full_table_dest["Dec_score"]=Dec_score

In [29]:
full_table_dest

,City,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,...,Mar_score,Apr_score,May_score,Jun_score,Jul_score,Aug_score,Sep_score,Oct_score,Nov_score,Dec_score
0,Vancouver,1.930376,2.391548,2.694355,2.589722,1.994086,2.113611,2.557258,2.558483,2.507363,...,4.0,3.0,2.0,2.0,3.0,3.0,3.0,3.0,4.0,3.0
1,Portland,2.172312,2.510047,2.327688,2.070556,1.748118,1.436944,2.104301,1.695699,1.668611,...,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0
2,San Francisco,2.350000,3.190603,3.139516,3.814722,3.398925,2.238611,2.827911,2.554570,2.623333,...,5.0,6.0,5.0,3.0,4.0,3.0,3.0,3.0,3.0,4.0
3,Seattle,1.712903,2.348109,2.454570,2.310278,1.915860,1.745833,2.068548,1.829032,2.049444,...,3.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0
4,Los Angeles,1.104570,0.959515,1.257258,1.464444,1.515591,1.189444,1.659677,1.319086,1.256111,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0
5,San Diego,1.447581,1.746749,1.835753,2.251389,2.105914,1.560833,1.972043,1.678226,1.818056,...,2.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
6,Las Vegas,2.164336,2.248522,2.722431,3.243401,3.177294,2.345833,2.955621,2.230645,2.262778,...,4.0,5.0,5.0,3.0,4.0,3.0,3.0,2.0,3.0,2.0
7,Phoenix,1.655645,1.617317,1.748319,2.275278,2.158871,2.014722,2.555108,2.049731,2.027500,...,2.0,3.0,2.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0
8,Albuquerque,2.456452,2.884752,3.233791,3.775000,3.216667,2.630833,2.910484,2.365323,2.568889,...,5.0,6.0,5.0,3.0,4.0,3.0,3.0,3.0,3.0,3.0
9,Denver,2.304301,3.267730,3.150578,3.101944,2.310484,1.816389,2.202688,2.042204,2.239167,...,5.0,5.0,3.0,2.0,3.0,2.0,3.0,3.0,3.0,3.0
10,San Antonio,2.754570,3.230496,3.371505,3.428333,3.680914,2.929167,3.300269,2.979570,2.629167,...,5.0,5.0,6.0,4.0,5.0,4.0,3.0,4.0,3.0,3.0
11,Dallas,3.400806,4.135934,4.054032,4.511944,3.992742,3.493889,3.554032,2.937634,3.084444,...,6.0,6.0,6.0,6.0,6.0,4.0,5.0,6.0,6.0,5.0
12,Houston,2.948656,3.519208,3.625538,3.621111,3.396774,2.623611,2.600538,2.501882,2.291667,...,6.0,6.0,5.0,3.0,3.0,3.0,3.0,3.0,4.0,4.0
13,Kansas City,3.343548,3.771572,3.929032,4.008333,3.334946,3.302778,3.243011,2.773387,3.103889,...,6.0,6.0,5.0,5.0,5.0,4.0,5.0,6.0,6.0,4.0
14,Minneapolis,3.201882,3.735520,3.732527,4.225833,3.551613,3.090000,3.022312,2.631791,3.189444,...,6.0,6.0,6.0,5.0,5.0,3.0,5.0,6.0,6.0,5.0
15,Saint Louis,3.378226,3.817671,3.708871,3.625833,2.904032,2.480000,2.437903,2.199462,2.453889,...,6.0,6.0,4.0,3.0,3.0,3.0,3.0,5.0,5.0,4.0
16,Chicago,4.158065,4.612884,4.199194,4.181111,3.399462,2.807778,3.194624,2.808602,3.257500,...,6.0,6.0,5.0,4.0,5.0,4.0,5.0,6.0,6.0,6.0
17,Nashville,2.686290,3.069740,3.110484,3.045556,2.302688,1.845790,1.937366,1.764991,1.827222,...,5.0,5.0,3.0,2.0,2.0,2.0,2.0,3.0,3.0,4.0
18,Indianapolis,3.644086,3.978132,4.033602,4.017778,3.294624,2.641389,2.723387,2.163978,2.280833,...,6.0,6.0,5.0,3.0,4.0,2.0,3.0,5.0,5.0,5.0
19,Atlanta,2.272849,2.734043,2.754839,2.581667,2.186559,1.935278,1.944086,1.855376,1.902500,...,4.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0
20,Detroit,3.457527,3.559693,3.452957,3.518056,3.144892,2.773056,2.637903,2.422849,2.613889,...,5.0,6.0,5.0,4.0,3.0,3.0,3.0,5.0,6.0,5.0
21,Jacksonville,2.883602,3.175827,3.173925,3.228889,2.872043,2.330000,2.750538,2.519624,2.513889,...,5.0,5.0,4.0,3.0,4.0,3.0,3.0,4.0,5.0,3.0
22,Charlotte,2.376882,2.869385,2.764785,2.853889,2.352419,1.957766,2.069892,2.009409,2.286944,...,4.0,4.0,3.0,2.0,2.0,2.0,3.0,3.0,3.0,2.0
23,Miami,3.090860,3.429669,3.413710,3.673056,3.344086,2.944722,2.969355,2.829032,2.877778,...,5.0,6.0,5.0,4.0,4.0,4.0,4.0,6.0,6.0,4.0
24,Pittsburgh,3.012634,3.197695,3.197581,3.103333,2.493280,1.857222,2.016667,1.613441,1.731667,...,5.0,5.0,3.0,2.0,2.0,2.0,2.0,3.0,4.0,4.0
25,Toronto,4.968548,5.229314,4.393548,4.449167,3.202151,2.688333,2.933333,2.739785,2.816111,...,6.0,6.0,5.0,4.0,4.0,4.0,4.0,6.0,6.0,6.0
26,Philadelphia,2.784409,3.268913,3.306720,3.127778,2.580645,2.130000,2.421619,1.985484,2.199722,...,5.0,5.0,3.0,2.0,3.0,2.0,3.0,3.0,4.0,3.0
27,New York,3.490054,3.764480,4.011022,3.881389,2.676613,2.323056,2.590323,2.552419,2.742222,...,6.0,6.0,3.0,3.0,3.0,3.0,4.0,5.0,6.0,5.0
28,Montreal,4.108871,4.195035,4.203226,4.378889,3.959946,3.073333,3.445968,3.271237,3.304167,...,6.0,6.0,6.0,5.0,5.0,5.0,5.0,6.0,6.0,6.0
29,Boston,3.676882,4.151596,4.204839,4.007778,3.173925,2.810556,2.839247,2.540054,3.002222,...,6.0,6.0,5.0,4.0,4.0,3.0,4.0,6.0,6.0,5.0
30,Beersheba,2.019086,1.997340,2.245699,2.201667,2.146774,2.125000,2.123387,2.056183,1.980000,...,3.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
31,Tel Aviv District,2.846505,2.637707,2.976613,2.908889,2.844851,2.529722,2.786290,2.829839,2.736944,...,4.0,4.0,4.0,3.0,4.0,4.0,4.0,3.0,3.0,3.0
32,Eilat,2.755376,2.555260,2.850806,2.957222,3.543280,4.052500,4.610484,4.270430,4.311111,...,4.0,4.0,6.0,6.0,6.0,6.0,6.0,5.0,5.0,4.0
33,Haifa,4.046774,3.937648,4.083625,3.565000,3.114247,2.826944,2.914516,2.710215,2.860833,...,6.0,6.0,5.0,4.0,4.0,4.0,4.0,4.0,5.0,5.0
34,Nahariyya,3.490860,3.205083,3.684593,3.103333,2.542742,2.614444,2.863978,2.668548,2.761111,...,6.0,5.0,3.0,3.0,4.0,3.0,4.0,4.0,5.0,5.0
35,Jerusalem,2.061828,2.054669,2.108065,2.087222,2.006722,1.634444,2.017204,1.896505,1.754444,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0

In [39]:
wind_score=full_table_dest.iloc [:,[0,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27]]

In [40]:
wind_score

,City,Country,Latitude,Longitude,Jan_score,Feb_score,Mar_score,Apr_score,May_score,Jun_score,Jul_score,Aug_score,Sep_score,Oct_score,Nov_score,Dec_score
0,Vancouver,Canada,49.249660,-123.119339,2.0,3.0,4.0,3.0,2.0,2.0,3.0,3.0,3.0,3.0,4.0,3.0
1,Portland,United States,45.523449,-122.676208,3.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0
2,San Francisco,United States,37.774929,-122.419418,3.0,5.0,5.0,6.0,5.0,3.0,4.0,3.0,3.0,3.0,3.0,4.0
3,Seattle,United States,47.606209,-122.332069,2.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0
4,Los Angeles,United States,34.052231,-118.243683,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0
5,San Diego,United States,32.715328,-117.157257,2.0,2.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
6,Las Vegas,United States,36.174969,-115.137222,3.0,3.0,4.0,5.0,5.0,3.0,4.0,3.0,3.0,2.0,3.0,2.0
7,Phoenix,United States,33.448380,-112.074043,2.0,2.0,2.0,3.0,2.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0
8,Albuquerque,United States,35.084492,-106.651138,3.0,4.0,5.0,6.0,5.0,3.0,4.0,3.0,3.0,3.0,3.0,3.0
9,Denver,United States,39.739151,-104.984703,3.0,5.0,5.0,5.0,3.0,2.0,3.0,2.0,3.0,3.0,3.0,3.0
10,San Antonio,United States,29.424120,-98.493629,4.0,5.0,5.0,5.0,6.0,4.0,5.0,4.0,3.0,4.0,3.0,3.0
11,Dallas,United States,32.783058,-96.806671,5.0,6.0,6.0,6.0,6.0,6.0,6.0,4.0,5.0,6.0,6.0,5.0
12,Houston,United States,29.763281,-95.363274,4.0,6.0,6.0,6.0,5.0,3.0,3.0,3.0,3.0,3.0,4.0,4.0
13,Kansas City,United States,39.099731,-94.578568,5.0,6.0,6.0,6.0,5.0,5.0,5.0,4.0,5.0,6.0,6.0,4.0
14,Minneapolis,United States,44.979969,-93.263840,5.0,6.0,6.0,6.0,6.0,5.0,5.0,3.0,5.0,6.0,6.0,5.0
15,Saint Louis,United States,38.627270,-90.197891,5.0,6.0,6.0,6.0,4.0,3.0,3.0,3.0,3.0,5.0,5.0,4.0
16,Chicago,United States,41.850029,-87.650047,6.0,6.0,6.0,6.0,5.0,4.0,5.0,4.0,5.0,6.0,6.0,6.0
17,Nashville,United States,36.165890,-86.784439,4.0,5.0,5.0,5.0,3.0,2.0,2.0,2.0,2.0,3.0,3.0,4.0
18,Indianapolis,United States,39.768379,-86.158043,6.0,6.0,6.0,6.0,5.0,3.0,4.0,2.0,3.0,5.0,5.0,5.0
19,Atlanta,United States,33.749001,-84.387978,3.0,4.0,4.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0
20,Detroit,United States,42.331429,-83.045753,5.0,6.0,5.0,6.0,5.0,4.0,3.0,3.0,3.0,5.0,6.0,5.0
21,Jacksonville,United States,30.332180,-81.655647,4.0,5.0,5.0,5.0,4.0,3.0,4.0,3.0,3.0,4.0,5.0,3.0
22,Charlotte,United States,35.227089,-80.843132,3.0,4.0,4.0,4.0,3.0,2.0,2.0,2.0,3.0,3.0,3.0,2.0
23,Miami,United States,25.774269,-80.193657,5.0,5.0,5.0,6.0,5.0,4.0,4.0,4.0,4.0,6.0,6.0,4.0
24,Pittsburgh,United States,40.440620,-79.995888,4.0,5.0,5.0,5.0,3.0,2.0,2.0,2.0,2.0,3.0,4.0,4.0
25,Toronto,Canada,43.700111,-79.416298,6.0,6.0,6.0,6.0,5.0,4.0,4.0,4.0,4.0,6.0,6.0,6.0
26,Philadelphia,United States,39.952339,-75.163788,4.0,5.0,5.0,5.0,3.0,2.0,3.0,2.0,3.0,3.0,4.0,3.0
27,New York,United States,40.714272,-74.005966,6.0,6.0,6.0,6.0,3.0,3.0,3.0,3.0,4.0,5.0,6.0,5.0
28,Montreal,Canada,45.508839,-73.587807,6.0,6.0,6.0,6.0,6.0,5.0,5.0,5.0,5.0,6.0,6.0,6.0
29,Boston,United States,42.358429,-71.059769,6.0,6.0,6.0,6.0,5.0,4.0,4.0,3.0,4.0,6.0,6.0,5.0
30,Beersheba,Israel,31.251810,34.791302,2.0,2.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
31,Tel Aviv District,Israel,32.083328,34.799999,4.0,3.0,4.0,4.0,4.0,3.0,4.0,4.0,4.0,3.0,3.0,3.0
32,Eilat,Israel,29.558050,34.948212,4.0,3.0,4.0,4.0,6.0,6.0,6.0,6.0,6.0,5.0,5.0,4.0
33,Haifa,Israel,32.815559,34.989170,6.0,6.0,6.0,6.0,5.0,4.0,4.0,4.0,4.0,4.0,5.0,5.0
34,Nahariyya,Israel,33.005859,35.094090,6.0,5.0,6.0,5.0,3.0,3.0,4.0,3.0,4.0,4.0,5.0,5.0
35,Jerusalem,Israel,31.769039,35.216331,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0

In [41]:
wind_score.to_csv("wind_scores1.csv",index=False)

In [33]:
pwd

'/Users/alexandersu/Documents/Vemgoo/In_Progress/historical-hourly-weather-data'