In [2]:
import numpy as np
import pandas as pd

In [6]:
cd DataSets/

/Users/alexandersu/Documents/Vemgoo/vmg-prelim/DataSets

In [10]:
wind=pd.read_csv('USA_wind.csv')
temp=pd.read_csv('USA_city_temps.csv')
city=pd.read_csv('city_attributes.csv')

In [15]:
#scoring for wind
Jan_score=[]

for x in wind['Jan']:
    if x > 3.49:
        Jan_score.append(float('6')),    
    elif x > 3.013:
        Jan_score.append(float('5')),
    elif x > 2.686:
        Jan_score.append(float('4')), 
    elif x > 2.164:
        Jan_score.append(float('3')),
    elif x > 1.104:
        Jan_score.append(float('2')), 
    else:
        Jan_score.append(float('1')),
city["Jan_score_temp"]=Jan_score

Feb_score=[]

for x in wind['Feb']:
    if x > 3.49:
        Feb_score.append(float('6')),    
    elif x > 3.013:
        Feb_score.append(float('5')),
    elif x > 2.686:
        Feb_score.append(float('4')), 
    elif x > 2.164:
        Feb_score.append(float('3')),
    elif x > 1.104:
        Feb_score.append(float('2')), 
    else:
        Feb_score.append(float('1')),

city["Feb_score_temp"]=Feb_score

Mar_score=[]
for x in wind['Mar']:
    if x > 3.49:
        Mar_score.append(float('6')),    
    elif x > 3.013:
        Mar_score.append(float('5')),
    elif x > 2.686:
        Mar_score.append(float('4')), 
    elif x > 2.164:
        Mar_score.append(float('3')),
    elif x > 1.104:
        Mar_score.append(float('2')), 
    else:
        Mar_score.append(float('1')),
city["Mar_score_temp"]=Mar_score

Apr_score=[]
for x in wind['Apr']:
    if x > 3.49:
        Apr_score.append(float('6')),    
    elif x > 3.013:
        Apr_score.append(float('5')),
    elif x > 2.686:
        Apr_score.append(float('4')), 
    elif x > 2.164:
        Apr_score.append(float('3')),
    elif x > 1.104:
        Apr_score.append(float('2')), 
    else:
        Apr_score.append(float('1')),
city["Apr_score_temp"]=Apr_score

May_score=[]
for x in wind['May']:
    if x > 3.49:
        May_score.append(float('6')),    
    elif x > 3.013:
        May_score.append(float('5')),
    elif x > 2.686:
        May_score.append(float('4')), 
    elif x > 2.164:
        May_score.append(float('3')),
    elif x > 1.104:
        May_score.append(float('2')), 
    else:
        May_score.append(float('1')),
city["May_score_temp"]=May_score

Jun_score=[]
for x in wind['Jun']:
    if x > 3.49:
        Jun_score.append(float('6')),    
    elif x > 3.013:
        Jun_score.append(float('5')),
    elif x > 2.686:
        Jun_score.append(float('4')), 
    elif x > 2.164:
        Jun_score.append(float('3')),
    elif x > 1.104:
        Jun_score.append(float('2')), 
    else:
        Jun_score.append(float('1')),
city["Jun_score_temp"]=Jun_score

Jul_score=[]
for x in wind['Jul']:
    if x > 3.49:
        Jul_score.append(float('6')),    
    elif x > 3.013:
        Jul_score.append(float('5')),
    elif x > 2.686:
        Jul_score.append(float('4')), 
    elif x > 2.164:
        Jul_score.append(float('3')),
    elif x > 1.104:
        Jul_score.append(float('2')), 
    else:
        Jul_score.append(float('1')),
city["Jul_score_temp"]=Jul_score

Aug_score=[]
for x in wind['Aug']:
    if x > 3.49:
        Aug_score.append(float('6')),    
    elif x > 3.013:
        Aug_score.append(float('5')),
    elif x > 2.686:
        Aug_score.append(float('4')), 
    elif x > 2.164:
        Aug_score.append(float('3')),
    elif x > 1.104:
        Aug_score.append(float('2')), 
    else:
        Aug_score.append(float('1')),
city["Aug_score_temp"]=Aug_score

Sep_score=[]
for x in wind['Sep']:
    if x > 3.49:
        Sep_score.append(float('6')),    
    elif x > 3.013:
        Sep_score.append(float('5')),
    elif x > 2.686:
        Sep_score.append(float('4')), 
    elif x > 2.164:
        Sep_score.append(float('3')),
    elif x > 1.104:
        Sep_score.append(float('2')), 
    else:
        Sep_score.append(float('1')),
city["Sep_score_temp"]=Sep_score

Oct_score=[]
for x in wind['Oct']:
    if x > 3.49:
        Oct_score.append(float('6')),    
    elif x > 3.013:
        Oct_score.append(float('5')),
    elif x > 2.686:
        Oct_score.append(float('4')), 
    elif x > 2.164:
        Oct_score.append(float('3')),
    elif x > 1.104:
        Oct_score.append(float('2')), 
    else:
        Oct_score.append(float('1')),
city["Oct_score_temp"]=Oct_score

Nov_score=[]
for x in wind['Nov']:
    if x > 3.49:
        Nov_score.append(float('6')),    
    elif x > 3.013:
        Nov_score.append(float('5')),
    elif x > 2.686:
        Nov_score.append(float('4')), 
    elif x > 2.164:
        Nov_score.append(float('3')),
    elif x > 1.104:
        Nov_score.append(float('2')), 
    else:
        Nov_score.append(float('1')),
city["Nov_score_temp"]=Nov_score


Dec_score=[]
for x in wind['Dec']:
    if x > 3.49:
        Dec_score.append(float('6')),    
    elif x > 3.013:
        Dec_score.append(float('5')),
    elif x > 2.686:
        Dec_score.append(float('4')), 
    elif x > 2.164:
        Dec_score.append(float('3')),
    elif x > 1.104:
        Dec_score.append(float('2')), 
    else:
        Dec_score.append(float('1')),
city["Dec_score_temp"]=Dec_score

In [16]:
#scoring for temperature
# For January
Jan_score=[]

for x in temp['Jan']:
    if x > 23.888:
        Jan_score.append(float('1'))
    elif x > 15.555:
        Jan_score.append(float('0.75'))
    elif x > 12.7: 
        Jan_score.append(float('0.5'))
    elif x > 10:
        Jan_score.append(float('0.25'))
    else:
        Jan_score.append(float('0'))
city["Jan_score_wind"]=Jan_score    

# For Feb
Feb_score=[]

for x in temp['Feb']:
    if x > 23.888:
        Feb_score.append(float('1'))
    elif x > 15.555:
        Feb_score.append(float('0.75'))
    elif x > 12.7: 
        Feb_score.append(float('0.5'))
    elif x > 10:
        Feb_score.append(float('0.25'))
    else:
        Feb_score.append(float('0'))
temp["Feb_score_wind"]=Feb_score      

# For March
Mar_score=[]

for x in temp['Mar']:
    if x > 23.888:
        Mar_score.append(float('1'))
    elif x > 15.555:
        Mar_score.append(float('0.75'))
    elif x > 12.7: 
        Mar_score.append(float('0.5'))
    elif x > 10:
        Mar_score.append(float('0.25'))
    else:
        Mar_score.append(float('0'))
city["Mar_score_wind"]=Mar_score        
        
# For April
Apr_score=[]

for x in temp['Apr']:
    if x > 23.888:
        Apr_score.append(float('1'))
    elif x > 15.555:
        Apr_score.append(float('0.75'))
    elif x > 12.7: 
        Apr_score.append(float('0.5'))
    elif x > 10:
        Apr_score.append(float('0.25'))
    else:
        Apr_score.append(float('0'))
city["Apr_score_wind"]=Apr_score

# For May
May_score=[]

for x in temp['May']:
    if x > 23.888:
        May_score.append(float('1'))
    elif x > 15.555:
        May_score.append(float('0.75'))
    elif x > 12.7: 
        May_score.append(float('0.5'))
    elif x > 10:
        May_score.append(float('0.25'))
    else:
        May_score.append(float('0'))
city["May_score_wind"]=May_score

# For June
Jun_score=[]

for x in temp['Jun']:
    if x > 23.888:
        Jun_score.append(float('1'))
    elif x > 15.555:
        Jun_score.append(float('0.75'))
    elif x > 12.7: 
        Jun_score.append(float('0.5'))
    elif x > 10:
        Jun_score.append(float('0.25'))
    else:
        Jun_score.append(float('0'))
city["Jun_score_wind"]=Jun_score

# For July
Jul_score=[]

for x in temp['Jul']:
    if x > 23.888:
        Jul_score.append(float('1'))
    elif x > 15.555:
        Jul_score.append(float('0.75'))
    elif x > 12.7: 
        Jul_score.append(float('0.5'))
    elif x > 10:
        Jul_score.append(float('0.25'))
    else:
        Jul_score.append(float('0'))
city["Jul_score_wind"]=Jul_score

# For August
Aug_score=[]

for x in temp['Aug']:
    if x > 23.888:
        Aug_score.append(float('1'))
    elif x > 15.555:
        Aug_score.append(float('0.75'))
    elif x > 12.7: 
        Aug_score.append(float('0.5'))
    elif x > 10:
        Aug_score.append(float('0.25'))
    else:
        Aug_score.append(float('0'))
city["Aug_score_wind"]=Aug_score

# For September
Sep_score = []

for x in temp['Sep']:
    if x > 23.888:
        Sep_score.append(float('1'))
    elif x > 15.555:
        Sep_score.append(float('0.75'))
    elif x > 12.7: 
        Sep_score.append(float('0.5'))
    elif x > 10:
        Sep_score.append(float('0.25'))
    else:
        Sep_score.append(float('0'))
city["Sep_score_wind"]=Sep_score

# For October
Oct_score = []

for x in temp['Oct']:
    if x > 23.888:
        Oct_score.append(float('1'))
    elif x > 15.555:
        Oct_score.append(float('0.75'))
    elif x > 12.7: 
        Oct_score.append(float('0.5'))
    elif x > 10:
        Oct_score.append(float('0.25'))
    else:
        Oct_score.append(float('0'))
city["Oct_score_wind"]=Oct_score

# For November
Nov_score = []

for x in temp['Nov']:
    if x > 23.888:
        Nov_score.append(float('1'))
    elif x > 15.555:
        Nov_score.append(float('0.75'))
    elif x > 12.7: 
        Nov_score.append(float('0.5'))
    elif x > 10:
        Nov_score.append(float('0.25'))
    else:
        Nov_score.append(float('0'))
city["Nov_score_wind"]=Nov_score

# For December
Dec_score = []

for x in temp['Dec']:
    if x > 23.888:
        Dec_score.append(float('1'))
    elif x > 15.555:
        Dec_score.append(float('0.75'))
    elif x > 12.7: 
        Dec_score.append(float('0.5'))
    elif x > 10:
        Dec_score.append(float('0.25'))
    else:
        Dec_score.append(float('0'))
city["Dec_score_wind"]=Dec_score

In [17]:
city

,City,Country,Latitude,Longitude,Jan_score,Feb_score,Mar_score,Apr_score,May_score,Jun_score,...,Mar_score_wind,Apr_score_wind,May_score_wind,Jun_score_wind,Jul_score_wind,Aug_score_wind,Sep_score_wind,Oct_score_wind,Nov_score_wind,Dec_score_wind
0,Vancouver,Canada,49.249660,-123.119339,0.00,3.0,0.00,0.00,0.50,0.75,...,0.00,0.00,0.50,0.75,0.75,0.75,0.50,0.25,0.00,0.00
1,Portland,United States,45.523449,-122.676208,0.00,3.0,0.00,0.25,0.50,0.75,...,0.00,0.25,0.50,0.75,0.75,0.75,0.75,0.25,0.00,0.00
2,San Francisco,United States,37.774929,-122.419418,0.25,5.0,0.50,0.50,0.75,0.75,...,0.50,0.50,0.75,0.75,0.75,0.75,0.75,0.75,0.50,0.25
3,Seattle,United States,47.606209,-122.332069,0.00,3.0,0.00,0.25,0.50,0.75,...,0.00,0.25,0.50,0.75,0.75,0.75,0.75,0.25,0.00,0.00
4,Los Angeles,United States,34.052231,-118.243683,0.25,1.0,0.50,0.75,0.75,0.75,...,0.50,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.50,0.25
5,San Diego,United States,32.715328,-117.157257,0.25,2.0,0.50,0.75,0.75,0.75,...,0.50,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.50,0.25
6,Las Vegas,United States,36.174969,-115.137222,0.00,3.0,0.75,0.75,0.75,1.00,...,0.75,0.75,0.75,1.00,1.00,1.00,1.00,0.75,0.25,0.00
7,Phoenix,United States,33.448380,-112.074043,0.25,2.0,0.75,0.75,1.00,1.00,...,0.75,0.75,1.00,1.00,1.00,1.00,1.00,0.75,0.75,0.25
8,Albuquerque,United States,35.084492,-106.651138,0.00,4.0,0.00,0.25,0.75,0.75,...,0.00,0.25,0.75,0.75,0.75,0.75,0.75,0.25,0.00,0.00
9,Denver,United States,39.739151,-104.984703,0.00,5.0,0.00,0.00,0.25,0.75,...,0.00,0.00,0.25,0.75,0.75,0.75,0.75,0.00,0.00,0.00
10,San Antonio,United States,29.424120,-98.493629,0.25,5.0,0.75,0.75,0.75,1.00,...,0.75,0.75,0.75,1.00,1.00,1.00,1.00,0.75,0.75,0.25
11,Dallas,United States,32.783058,-96.806671,0.00,6.0,0.50,0.75,0.75,1.00,...,0.50,0.75,0.75,1.00,1.00,1.00,1.00,0.75,0.50,0.00
12,Houston,United States,29.763281,-95.363274,0.25,6.0,0.75,0.75,0.75,1.00,...,0.75,0.75,0.75,1.00,1.00,1.00,1.00,0.75,0.75,0.50
13,Kansas City,United States,39.099731,-94.578568,0.00,6.0,0.00,0.50,0.75,1.00,...,0.00,0.50,0.75,1.00,1.00,1.00,0.75,0.50,0.00,0.00
14,Minneapolis,United States,44.979969,-93.263840,0.00,6.0,0.00,0.00,0.50,0.75,...,0.00,0.00,0.50,0.75,0.75,0.75,0.75,0.00,0.00,0.00
15,Saint Louis,United States,38.627270,-90.197891,0.00,6.0,0.00,0.50,0.75,1.00,...,0.00,0.50,0.75,1.00,1.00,1.00,0.75,0.50,0.00,0.00
16,Chicago,United States,41.850029,-87.650047,0.00,6.0,0.00,0.00,0.50,0.75,...,0.00,0.00,0.50,0.75,0.75,0.75,0.75,0.50,0.00,0.00
17,Nashville,United States,36.165890,-86.784439,0.00,5.0,0.00,0.75,0.75,1.00,...,0.00,0.75,0.75,1.00,1.00,1.00,0.75,0.75,0.00,0.00
18,Indianapolis,United States,39.768379,-86.158043,0.00,6.0,0.00,0.25,0.75,0.75,...,0.00,0.25,0.75,0.75,0.75,0.75,0.75,0.50,0.00,0.00
19,Atlanta,United States,33.749001,-84.387978,0.00,4.0,0.25,0.75,0.75,1.00,...,0.25,0.75,0.75,1.00,1.00,1.00,0.75,0.75,0.25,0.00
20,Detroit,United States,42.331429,-83.045753,0.00,6.0,0.00,0.00,0.50,0.75,...,0.00,0.00,0.50,0.75,0.75,0.75,0.75,0.25,0.00,0.00
21,Jacksonville,United States,30.332180,-81.655647,0.50,5.0,0.75,0.75,0.75,1.00,...,0.75,0.75,0.75,1.00,1.00,1.00,1.00,0.75,0.75,0.75
22,Charlotte,United States,35.227089,-80.843132,0.00,4.0,0.25,0.75,0.75,1.00,...,0.25,0.75,0.75,1.00,1.00,1.00,0.75,0.75,0.00,0.00
23,Miami,United States,25.774269,-80.193657,0.75,5.0,0.75,1.00,1.00,1.00,...,0.75,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.75,0.75
24,Pittsburgh,United States,40.440620,-79.995888,0.00,5.0,0.00,0.25,0.75,0.75,...,0.00,0.25,0.75,0.75,0.75,0.75,0.75,0.25,0.00,0.00
25,Toronto,Canada,43.700111,-79.416298,0.00,6.0,0.00,0.00,0.50,0.75,...,0.00,0.00,0.50,0.75,0.75,0.75,0.75,0.25,0.00,0.00
26,Philadelphia,United States,39.952339,-75.163788,0.00,5.0,0.00,0.25,0.75,0.75,...,0.00,0.25,0.75,0.75,1.00,0.75,0.75,0.50,0.00,0.00
27,New York,United States,40.714272,-74.005966,0.00,6.0,0.00,0.25,0.75,0.75,...,0.00,0.25,0.75,0.75,1.00,0.75,0.75,0.50,0.00,0.00
28,Montreal,Canada,45.508839,-73.587807,0.00,6.0,0.00,0.00,0.50,0.75,...,0.00,0.00,0.50,0.75,0.75,0.75,0.75,0.25,0.00,0.00
29,Boston,United States,42.358429,-71.059769,0.00,6.0,0.00,0.00,0.50,0.75,...,0.00,0.00,0.50,0.75,0.75,0.75,0.75,0.50,0.00,0.00
30,Beersheba,Israel,31.251810,34.791302,0.00,2.0,0.50,0.75,0.75,0.75,...,0.50,0.75,0.75,0.75,1.00,1.00,0.75,0.75,0.50,0.25
31,Tel Aviv District,Israel,32.083328,34.799999,0.50,3.0,0.75,0.75,0.75,1.00,...,0.75,0.75,0.75,1.00,1.00,1.00,1.00,0.75,0.75,0.50
32,Eilat,Israel,29.558050,34.948212,0.50,3.0,0.75,0.75,1.00,1.00,...,0.75,0.75,1.00,1.00,1.00,1.00,1.00,1.00,0.75,0.50
33,Haifa,Israel,32.815559,34.989170,0.50,6.0,0.75,0.75,0.75,1.00,...,0.75,0.75,0.75,1.00,1.00,1.00,1.00,1.00,0.75,0.75
34,Nahariyya,Israel,33.005859,35.094090,0.50,5.0,0.75,0.75,0.75,1.00,...,0.75,0.75,0.75,1.00,1.00,1.00,1.00,0.75,0.75,0.50
35,Jerusalem,Israel,31.769039,35.216331,0.25,2.0,0.75,0.75,0.75,1.00,...,0.75,0.75,0.75,1.00,1.00,1.00,1.00,0.75,0.75,0.50